// Cross-repo parity gate (M2 plan §2): the vendored pure helpers must produce
// byte-identical hashes and token numbers to gaia-research's census.ts on the
// same input. The fixture (test/fixtures/census-parity.json) was generated by
// running the real census.ts over test/fixtures/impeccable-skill; regenerate
// it with:
//   npx tsx scripts/hell-heaven-bench/census.ts --repo <tmp repo containing
//     .agents/skills/impeccable copied from test/fixtures/impeccable-skill> --json out.json
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { resolveSkill } from "../src/skills.js";
import { makeListingLine, tokenize } from "../src/vendor/census-pure.js";

const fixturesDir = join(import.meta.dirname, "fixtures");
const fixture = JSON.parse(readFileSync(join(fixturesDir, "census-parity.json"), "utf-8"));

describe("census parity (vendored helpers vs gaia-research census.ts)", () => {
  const skill = resolveSkill(join(fixturesDir, "impeccable-skill"));

  it("same id", () => {
    expect(skill.id).toBe(fixture.record.id);
  });
  it("same contentSha256 (SkillRef shape)", () => {
    expect(skill.contentSha256).toBe(fixture.record.contentSha256);
  });
  it("same standing dose (listing line, chars4)", () => {
    expect(skill.standingTokens).toBe(fixture.record.standingTokens);
  });
  it("same invocation dose (full SKILL.md, chars4)", () => {
    expect(skill.invocationTokens).toBe(fixture.record.invocationTokens);
  });
  it("tokenizer backend matches", () => {
    expect(fixture.tokenizer).toBe("chars4");
  });
  it("chars4 formula spot-checks", () => {
    expect(tokenize("")).toBe(1); // max(1, …)
    expect(tokenize("abcd")).toBe(1);
    expect(tokenize("abcdefgh")).toBe(2);
    expect(makeListingLine("x", "a   b\n c")).toBe("- x: a b c");
  });
});
