// GENERATED by scripts/build-status.mjs from packages/status/src — do not edit.
// One status model for every projection (docs/CONTROL-PLANE.md).
// packages/status/src/model.ts
var RUNGS = ["zero", "low", "med", "high", "xhigh", "max", "ultra"];
var RUNG_BAND = Object.freeze({
  zero: "zero",
  low: "heaven",
  med: "heaven",
  high: "hell",
  xhigh: "hell",
  max: "hell",
  ultra: "ultra"
});
function bandOf(rung) {
  return RUNG_BAND[rung];
}
function readingRung(reading) {
  if (reading.kind === "selected") return reading.rung;
  if (reading.kind === "boot" && reading.posture === "product-floor") return "zero";
  return null;
}
function isRung(value) {
  return typeof value === "string" && RUNGS.includes(value);
}
function emptyStatus() {
  return {
    reading: { kind: "unknown" },
    skills: null,
    summons: null,
    lastArrival: null,
    controller: { kind: "not-selected" },
    summonTool: "unknown"
  };
}

// packages/status/src/sanitize.ts
var ANSI = /\u001b(?:\[[0-?]*[ -/]*[@-~]|\][^\u0007\u001b]*(?:\u0007|\u001b\\)|[@-Z\\-_])/g;
var CONTROLS = /[\u0000-\u001f\u007f-\u009f]/g;
var BIDI = /[‎‏‪-‮⁦-⁩]/g;
var RESERVED = /* @__PURE__ */ new Map([
  ["\u25C7", "*"],
  ["\u25C6", "*"],
  ["\u2039", "<"],
  ["\u203A", ">"],
  ["\xD7", "x"]
]);
var DEFAULT_FIELD_LIMIT = 48;
function sanitizeDisplay(value, limit = DEFAULT_FIELD_LIMIT) {
  if (value === null || value === void 0) return "";
  let text = String(value).replace(ANSI, "").replace(BIDI, "").replace(CONTROLS, " ");
  let out = "";
  for (const ch of text) out += RESERVED.get(ch) ?? ch;
  text = out.replace(/\s+/g, " ").trim();
  const chars = Array.from(text);
  if (limit > 0 && chars.length > limit) return chars.slice(0, Math.max(1, limit - 1)).join("") + "\u2026";
  return text;
}
function cellWidth(text) {
  let width = 0;
  for (const ch of text) {
    const code = ch.codePointAt(0) ?? 0;
    width += isWide(code) ? 2 : 1;
  }
  return width;
}
function isWide(code) {
  return code >= 4352 && code <= 4447 || code >= 11904 && code <= 42191 || code >= 44032 && code <= 55203 || code >= 63744 && code <= 64255 || code >= 65072 && code <= 65103 || code >= 65280 && code <= 65376 || code >= 65504 && code <= 65510 || code >= 127744 && code <= 129791 || code >= 131072 && code <= 262141;
}

// packages/status/src/tokens.ts
var ROLE_COLORS = Object.freeze({
  umbrella: { hex: "#a58ae0", ansi256: 141, ansi16: 35, cssVar: "--sh-violet" },
  ultra: { hex: "#d9b25c", ansi256: 179, ansi16: 33, cssVar: "--sh-ultra" },
  zero: { hex: "#5fc2d6", ansi256: 80, ansi16: 36, cssVar: "--sh-zero" },
  heaven: { hex: "#6f96d8", ansi256: 68, ansi16: 34, cssVar: "--sh-heaven" },
  hell: { hex: "#e094c8", ansi256: 175, ansi16: 95, cssVar: "--sh-hell" },
  ink: { hex: "#eeebe6", ansi256: 255, ansi16: 39, cssVar: "--sh-bone" },
  dim: { hex: "#9a9691", ansi256: 246, ansi16: 90, cssVar: "--sh-dim" },
  arbor: { hex: "#55c878", ansi256: 77, ansi16: 32, cssVar: "--sh-arbor" },
  stop: { hex: "#c81e1e", ansi256: 160, ansi16: 31, cssVar: "--sh-stop" },
  amber: { hex: "#e0b45c", ansi256: 179, ansi16: 33, cssVar: "--sh-amber" }
});
var GROUND_HEX = "#1b1a1c";

// packages/status/src/render.ts
var SEP = { text: " \xB7 ", role: "dim" };
var seg = (text, role) => ({ text, role });
function readingToken(reading) {
  switch (reading.kind) {
    case "selected":
      return reading.rung.toUpperCase();
    case "boot":
      return reading.posture === "product-floor" ? "ZERO" : reading.posture === "curated" ? "CURATED" : "NATIVE";
    case "native":
      return "NATIVE";
    case "unknown":
      return "?";
  }
}
function readingRole(reading) {
  const rung = readingRung(reading);
  if (!rung) return "ink";
  const band = RUNG_BAND[rung];
  return band === "zero" ? "zero" : band === "heaven" ? "heaven" : band === "hell" ? "hell" : "ultra";
}
function isUltra(status) {
  return readingRung(status.reading) === "ultra";
}
function skillsText(n, short) {
  if (n === null) return short ? "?" : "? skills";
  if (short) return String(n);
  return `${n} ${n === 1 ? "skill" : "skills"}`;
}
function readingSegments(status) {
  return [
    seg("\u2039\u2039", "heaven"),
    seg(" ", "dim"),
    seg(`[${readingToken(status.reading)}]`, readingRole(status.reading)),
    seg(" ", "dim"),
    seg("\u203A\u203A", "hell")
  ];
}
function headSegments(status, withWord) {
  const ultra = isUltra(status);
  const out = [];
  if (status.fixture || status.controller.kind === "fixture") out.push(seg("FIXTURE", "amber"), seg(" ", "dim"));
  out.push(seg(ultra ? "\u25C6" : "\u25C7", ultra ? "ultra" : "umbrella"));
  if (withWord) out.push(seg(" entropy", "umbrella"));
  out.push(seg(" ", "dim"), ...readingSegments(status));
  return out;
}
function controllerSegments(controller, opts = { progress: true }) {
  switch (controller.kind) {
    case "not-selected":
      return [];
    case "unavailable":
      return [SEP, seg("controller unavailable", "dim")];
    case "reported":
    case "fixture": {
      const out = [SEP, seg(sanitizeDisplay(controller.state, 24).toUpperCase(), "ultra")];
      if (controller.effective) {
        const band = RUNG_BAND[controller.effective];
        const role = band === "heaven" ? "heaven" : "hell";
        out.push(SEP, seg("now ", "dim"), seg(controller.effective.toUpperCase(), role), seg(band === "heaven" ? " \u2039" : " \u203A", role));
      }
      if (opts.progress && controller.progress) {
        out.push(SEP, seg(`${controller.progress.completed}/${controller.progress.total}`, "ink"));
      }
      return out;
    }
  }
}
function statusLevels(status, mode) {
  if (mode === "off") return [];
  const ultra = isUltra(status);
  const controller = ultra ? status.controller : { kind: "not-selected" };
  const skills = [SEP, seg(skillsText(status.skills, false), "ink")];
  const summons = status.summons === null ? [] : [seg(" / ", "dim"), seg(`${status.summons} ${status.summons === 1 ? "summon" : "summons"}`, "dim")];
  const arrival = status.lastArrival ? [SEP, seg(`+${sanitizeDisplay(status.lastArrival, 32)}`, "ink")] : [];
  const full = [
    [...headSegments(status, true), ...skills, ...summons, ...controllerSegments(controller), ...arrival],
    [...headSegments(status, true), ...skills, ...summons, ...controllerSegments(controller)],
    [...headSegments(status, true), ...skills, ...controllerSegments(controller)],
    [...headSegments(status, true), ...skills, ...controllerSegments(controller, { progress: false })]
  ];
  const compact = [
    [...headSegments(status, true), ...skills],
    [...headSegments(status, false), SEP, seg(skillsText(status.skills, true), "ink")],
    [...headSegments(status, false)]
  ];
  const bare = [];
  if (status.fixture || status.controller.kind === "fixture") bare.push(seg("FIXTURE", "amber"), seg(" ", "dim"));
  bare.push(seg(`[${readingToken(status.reading)}]`, readingRole(status.reading)));
  return mode === "full" ? [...full, ...compact, bare] : [...compact, bare];
}
function segmentsWidth(segments) {
  return segments.reduce((sum, s) => sum + cellWidth(s.text), 0);
}
function renderStatusSegments(status, mode, width) {
  const levels = statusLevels(status, mode);
  if (levels.length === 0) return [];
  if (width === void 0 || !Number.isFinite(width)) return levels[0];
  return levels.find((level) => segmentsWidth(level) <= width) ?? levels[levels.length - 1];
}
function directionGlyph(direction) {
  if (direction === "converge") return seg("\u2039", "heaven");
  if (direction === "explore") return seg("\u203A", "hell");
  return seg("\u25C7", "umbrella");
}
function formatScore(value) {
  if (value === null || !Number.isFinite(value)) return null;
  const clamped = Math.max(0, Math.min(1, value));
  return clamped >= 1 ? "1.00" : clamped.toFixed(2).replace(/^0/, "");
}
function formatMs(ms) {
  if (ms === null || !Number.isFinite(ms) || ms < 0) return null;
  return ms < 1e3 ? `${Math.round(ms)}ms` : `${(ms / 1e3).toFixed(2)}s`;
}
var CLOSE_CALL_MARGIN = 0.1;
function receiptDetail(skill, delta) {
  const parts = [];
  if (skill.matchKind !== "unknown") parts.push(skill.matchKind);
  const score = formatScore(skill.score);
  if (score) parts.push(score);
  const margin = formatScore(skill.margin);
  if (margin) parts.push(`\u0394 ${margin}`);
  if (skill.cache !== "unknown") parts.push(skill.cache);
  const ms = formatMs(skill.ms);
  if (ms) parts.push(ms);
  if (delta !== null) parts.push(`+${delta}`);
  return [seg("  ", "dim"), seg(parts.join(" \xB7 ") || "no ranking disclosure", "dim")];
}
function eventLines(event) {
  const lines = eventLinesInner(event);
  if (event.evidence === "fixture" && lines[0]) lines[0] = [seg("FIXTURE", "amber"), seg(" ", "dim"), ...lines[0]];
  return lines;
}
function eventLinesInner(event) {
  switch (event.kind) {
    case "summoned": {
      const [first, ...rest] = event.skills;
      const line1 = [directionGlyph(event.direction), seg(" summoned  ", "dim")];
      line1.push(seg(first ? sanitizeDisplay(first.name, 40) : "nothing", "ink"));
      if (rest.length > 0) line1.push(seg(` +${rest.length} more`, "dim"));
      const line2 = first ? receiptDetail(first, event.delta) : [seg("  ", "dim"), seg("no skill in result", "dim")];
      if (event.sourceHealth.kind === "stale") line2.push(SEP, seg("? index stale", "amber"));
      return [line1, line2];
    }
    case "previewed": {
      const [first] = event.skills;
      const line1 = [seg("\u25C7", "umbrella"), seg(" lens  ", "dim")];
      if (event.skills.length === 1 && first) line1.push(seg(sanitizeDisplay(first.name, 40), "ink"));
      else line1.push(seg(`${event.skills.length} candidates`, "ink"));
      const parts = [seg("  ", "dim"), seg("nothing materialized", "dim")];
      if (first && event.skills.length > 1) parts.push(SEP, seg(`top ${sanitizeDisplay(first.name, 32)}`, "dim"));
      if (first?.margin !== null && first?.margin !== void 0 && first.margin < CLOSE_CALL_MARGIN && event.skills.length > 1) {
        parts.push(SEP, seg(`\u0394 ${formatScore(first.margin)} close call (retrieval)`, "dim"));
      }
      return [line1, parts];
    }
    case "no-match": {
      const detail = event.considered === null ? "0 admitted" : `${event.considered} considered \xB7 0 admitted`;
      const reason = event.reason ? ` \xB7 ${sanitizeDisplay(event.reason, 60)}` : "";
      const tail = event.preview ? " \xB7 nothing materialized" : "";
      return [
        [seg("\u25C7", "umbrella"), seg(event.preview ? " lens  " : " summon  ", "dim"), seg("\xD7", "ink"), seg(" no match", "ink")],
        [seg("  ", "dim"), seg(detail + reason + tail, "dim")]
      ];
    }
    case "unavailable":
      return [
        [seg("\u25C7", "umbrella"), seg(" summon  ", "dim"), seg("?", "amber"), seg(" unavailable", "ink")],
        [seg("  ", "dim"), seg(sanitizeDisplay(event.reason, 72), "dim")]
      ];
    case "error":
      return [
        [seg("\u25C7", "umbrella"), seg(" summon  ", "dim"), seg("!", "stop"), seg(" failed", "ink")],
        [seg("  ", "dim"), seg(sanitizeDisplay(event.reason, 72), "dim")]
      ];
  }
}
function noticeLines(notice) {
  if (notice.kind === "looking") {
    return [
      [seg("\u25C7", "umbrella"), seg(" lens  ", "dim"), seg("looking\u2026", "ink")],
      [seg("  ", "dim"), seg(`${sanitizeDisplay(notice.query, 48)} \xB7 nothing materialized`, "dim")]
    ];
  }
  return [
    [seg("\u25C7", "umbrella"), seg(" summon  ", "dim"), seg("?", "amber"), seg(" not connected", "ink")],
    [seg("  ", "dim"), seg("the summon tool is not available in this session", "dim")]
  ];
}
function describeReading(reading) {
  switch (reading.kind) {
    case "selected":
      return `${reading.rung}, the rung you selected (not enforced)`;
    case "boot":
      return reading.posture === "product-floor" ? "zero, the Skill Zero floor set at launch" : reading.posture === "curated" ? "curated, set at launch" : "native, your harness's own skills";
    case "native":
      return "native, your harness's own skills";
    case "unknown":
      return "unknown";
  }
}
function describeStatus(status) {
  const parts = [`Skill entropy reading: ${describeReading(status.reading)}.`];
  parts.push(
    status.skills === null ? "Skills in this session: unknown." : `${status.skills} ${status.skills === 1 ? "skill" : "skills"} materialized in this session.`
  );
  if (isUltra(status)) {
    const c = status.controller;
    if (c.kind === "unavailable") parts.push("Ultra controller: unavailable; nothing is choosing for you yet.");
    else if (c.kind === "reported" || c.kind === "fixture") {
      parts.push(`Ultra controller: ${sanitizeDisplay(c.state, 24).toLowerCase()}${c.effective ? `, working at ${c.effective}` : ""}.`);
    }
  }
  if (status.fixture || status.controller.kind === "fixture") parts.unshift("Fixture, design state only.");
  return parts.join(" ");
}
function describeEvent(event) {
  const text = describeEventInner(event);
  return event.evidence === "fixture" ? `Fixture, design state only. ${text}` : text;
}
function describeEventInner(event) {
  const how = event.direction === "converge" ? "converging" : event.direction === "explore" ? "exploring" : event.direction === "manual" ? "by hand" : "";
  switch (event.kind) {
    case "summoned": {
      const names = event.skills.map((s) => sanitizeDisplay(s.name, 40)).join(", ") || "nothing";
      return `Summoned ${names}${how ? `, ${how}` : ""}. A card was returned; ${event.delta} added to the session.`;
    }
    case "previewed":
      return `Lens preview: ${event.skills.length} candidate${event.skills.length === 1 ? "" : "s"}; nothing materialized.`;
    case "no-match":
      return event.preview ? "Lens preview found no match. Nothing was materialized." : "Summon found no match. Nothing was added to the session.";
    case "unavailable":
      return `Summon unavailable: ${sanitizeDisplay(event.reason, 72)}.`;
    case "error":
      return `Summon failed: ${sanitizeDisplay(event.reason, 72)}.`;
  }
}
function resolveColorDepth(env, isTTY = true) {
  if (env.NO_COLOR !== void 0 && env.NO_COLOR !== "") return "none";
  if (!isTTY && env.FORCE_COLOR === void 0) return "none";
  const term = env.TERM ?? "";
  if (term === "dumb") return "none";
  const colorterm = (env.COLORTERM ?? "").toLowerCase();
  if (colorterm === "truecolor" || colorterm === "24bit") return "truecolor";
  if (term.includes("256")) return "256";
  return "16";
}
function sgr(role, depth) {
  const c = ROLE_COLORS[role];
  if (depth === "truecolor") {
    const n = parseInt(c.hex.slice(1), 16);
    return `\x1B[38;2;${n >> 16 & 255};${n >> 8 & 255};${n & 255}m`;
  }
  if (depth === "256") return `\x1B[38;5;${c.ansi256}m`;
  return `\x1B[${c.ansi16}m`;
}
function paintAnsi(segments, depth) {
  if (depth === "none") return toPlain(segments);
  return segments.map((s) => s.role === "dim" && s.text.trim() === "" ? s.text : `${sgr(s.role, depth)}${s.text}\x1B[39m`).join("");
}
function toPlain(segments) {
  return segments.map((s) => s.text).join("");
}

// packages/status/src/adapters.ts
var isRec = (v) => typeof v === "object" && v !== null && !Array.isArray(v);
var str = (v) => typeof v === "string" && v.length > 0 ? v : null;
var num = (v) => typeof v === "number" && Number.isFinite(v) ? v : null;
function readingFromProfileManifest(manifest) {
  if (!isRec(manifest) || manifest.schema !== "claude-zero/profile@1") return { kind: "unknown" };
  const posture = manifest.posture;
  if (posture === "product-floor" || posture === "curated" || posture === "native") {
    return { kind: "boot", posture, source: "launcher-manifest" };
  }
  return { kind: "unknown" };
}
var BAND_COMMANDS = [
  { command: "skill-zero", rungs: ["zero"], fallback: "zero" },
  { command: "skill-heaven", rungs: ["low", "med"], fallback: "low" },
  { command: "skill-hell", rungs: ["high", "xhigh", "max"], fallback: "high" },
  { command: "skill-ultra", rungs: ["ultra"], fallback: "ultra" }
];
function selectionFromCommand(text) {
  const match = /^\s*\/(?:[a-z0-9-]+:)?(skill-zero|skill-heaven|skill-hell|skill-ultra)(?:\s+(\S+))?\s*$/i.exec(text);
  if (!match) return null;
  const entry = BAND_COMMANDS.find((b) => b.command === match[1].toLowerCase());
  const arg = match[2]?.toLowerCase();
  if (!arg) return { kind: "selected", rung: entry.fallback, source: "observed-command" };
  if (entry.command === "skill-zero") return arg === "all" ? { kind: "selected", rung: "zero", source: "observed-command" } : null;
  if (isRung(arg) && entry.rungs.includes(arg)) return { kind: "selected", rung: arg, source: "observed-command" };
  return null;
}
function withReading(status, reading) {
  const ultra = reading.kind === "selected" && reading.rung === "ultra";
  const boot = status.boot ?? (status.reading.kind === "selected" || status.reading.kind === "unknown" ? void 0 : status.reading);
  const controller = ultra ? status.controller.kind === "reported" ? status.controller : { kind: "unavailable" } : { kind: "not-selected" };
  return { ...status, reading, controller, ...boot ? { boot } : {} };
}
function skillsFromSessionManifest(manifest) {
  if (!isRec(manifest) || !Array.isArray(manifest.skills)) return { skills: null, last: null };
  const entries = manifest.skills.filter((s) => isRec(s) && typeof s.id === "string");
  if (entries.length !== manifest.skills.length) return { skills: null, last: null };
  const last = entries.length > 0 ? entries[entries.length - 1] : null;
  return { skills: entries.length, last: last ? str(last.name) ?? str(last.id) : null };
}
function directionFromSurface(surface) {
  if (surface === "any") return "manual";
  if (surface === "heaven") return "converge";
  if (surface === "hell") return "explore";
  return "unspecified";
}
function laneOf(skill) {
  if (skill.invocation === "human") return "human-led";
  if (skill.invocation === "model") return "model-led";
  if (skill.invocation === "any") return "unspecified";
  return "unknown";
}
function receiptFrom(skill, stage, agent) {
  const retrieval = isRec(skill.retrieval) ? skill.retrieval : {};
  const matchKind = retrieval.matchKind === "exact" || retrieval.matchKind === "ranked" ? retrieval.matchKind : "unknown";
  const cacheRaw = skill.cacheState ?? skill.cache;
  const totalSeconds = num(skill.totalSeconds);
  const installability = isRec(skill.installability) ? str(skill.installability.state) ?? "unknown" : "unknown";
  return {
    id: str(skill.id) ?? "unknown",
    name: str(skill.name) ?? str(skill.id) ?? "unknown",
    stage,
    matchKind,
    score: num(retrieval.score) ?? num(skill.score),
    margin: num(retrieval.margin) ?? num(skill.margin),
    cache: cacheRaw === "cold" || cacheRaw === "warm" ? cacheRaw : "unknown",
    ms: totalSeconds === null ? null : Math.round(totalSeconds * 1e3),
    lane: laneOf(skill),
    source: str(skill.source),
    repoUrl: str(skill.repoUrl),
    ref: str(skill.branch),
    sourceUrl: str(skill.sourceUrl),
    subpath: str(skill.subpath),
    sha256: str(skill.sha256),
    path: str(skill.path),
    installability,
    agent
  };
}
function sourceHealthOf(result) {
  const ranking = isRec(result.ranking) ? result.ranking : null;
  if (!ranking || typeof ranking.stale !== "boolean") return { kind: "unknown" };
  const age = num(ranking.indexAgeDays);
  const indexAgeDays = age === null ? null : Math.floor(age);
  return ranking.stale ? { kind: "stale", indexAgeDays } : { kind: "fresh", indexAgeDays };
}
function arborOf(result, summoned) {
  const arbor = isRec(result.arbor) ? result.arbor : null;
  if (!arbor) return "unknown";
  if (arbor.publicationState === "unavailable" || arbor.publicationState === "unreadable") return "unavailable";
  if (arbor.publicationState !== "loaded") return "unknown";
  return summoned.some((s) => isRec(s.arbor) && s.arbor.join === "content-pinned") ? "governed-record" : "no-record";
}
var NO_MATCH_REASON = {
  no_candidates: "no candidates in the source",
  below_floor: "nothing cleared the relevance floor",
  all_filtered: "every candidate was outside this lane"
};
function eventFromSummonResult(structured, call = {}, failure) {
  const at = call.at ?? null;
  const agent = call.agent ?? null;
  if (failure?.isError) {
    const text = failure.text ?? "the summon tool reported an error";
    const unavailable = /unresolvable|unreachable|ENOTFOUND|EAI_AGAIN|fetch failed|network|offline/i.test(text);
    return {
      kind: unavailable ? "unavailable" : "error",
      direction: "unspecified",
      query: call.query ?? "",
      preview: call.preview === true,
      reason: text,
      at,
      evidence: "observed"
    };
  }
  if (!isRec(structured)) {
    return {
      kind: "error",
      direction: "unspecified",
      query: call.query ?? "",
      preview: call.preview === true,
      reason: "the summon result had no structured content",
      at,
      evidence: "observed"
    };
  }
  const direction = directionFromSurface(structured.surface);
  const query = str(structured.query) ?? call.query ?? "";
  const sourceHealth = sourceHealthOf(structured);
  if (structured.noMatch !== null && structured.noMatch !== void 0) {
    const noMatch = isRec(structured.noMatch) ? structured.noMatch : {};
    const reason = typeof noMatch.reason === "string" ? NO_MATCH_REASON[noMatch.reason] ?? null : null;
    return { kind: "no-match", direction, query, preview: call.preview === true, considered: null, reason, at, evidence: "reported", sourceHealth };
  }
  const summoned = Array.isArray(structured.summoned) ? structured.summoned.filter(isRec) : [];
  const previewed = Array.isArray(structured.previewed) ? structured.previewed.filter(isRec) : [];
  if (summoned.length === 0 && (previewed.length > 0 || call.preview === true)) {
    return {
      kind: "previewed",
      direction,
      query,
      skills: previewed.map((s) => receiptFrom(s, "previewed", agent)),
      delta: 0,
      preview: true,
      at,
      evidence: "reported",
      sourceHealth
    };
  }
  const skipped = Array.isArray(structured.skipped) ? structured.skipped : [];
  if (summoned.length === 0 && skipped.length > 0) {
    const first = skipped[0];
    const why = isRec(first) ? str(first.why) ?? str(first.reason) ?? str(first.error) : str(first);
    return {
      kind: "error",
      direction,
      query,
      preview: call.preview === true,
      reason: why ? `nothing materialized: ${why}` : "nothing materialized: every candidate was skipped",
      at,
      evidence: "reported"
    };
  }
  const composition = isRec(structured.composition) && structured.composition.mode === "relevance-only" ? "relevance-only" : "unknown";
  return {
    kind: "summoned",
    direction,
    query,
    skills: summoned.map((s) => receiptFrom(s, "materialized", agent)),
    delta: summoned.length,
    preview: false,
    at,
    evidence: "reported",
    composition,
    arbor: arborOf(structured, summoned),
    sourceHealth
  };
}
function reduceStatus(status, event) {
  if (event.kind === "previewed" || event.kind !== "summoned" && event.preview) return status;
  const summons = status.summons === null ? null : status.summons + 1;
  if (event.kind !== "summoned") return { ...status, summons };
  const skills = status.skills === null ? null : status.skills + event.delta;
  const last = event.skills[event.skills.length - 1];
  return { ...status, skills, summons, lastArrival: last ? last.name : status.lastArrival };
}
function markRead(event, readPath) {
  if (event.kind !== "summoned") return event;
  const norm = readPath.replace(/\\/g, "/");
  let changed = false;
  const skills = event.skills.map((s) => {
    if (!s.path || s.stage === "in-context") return s;
    let root = s.path.replace(/\\/g, "/");
    while (root.endsWith("/")) root = root.slice(0, -1);
    if (norm === `${root}/SKILL.md`) {
      changed = true;
      return { ...s, stage: "in-context" };
    }
    return s;
  });
  return changed ? { ...event, skills } : event;
}
var STEERING_DECISIONS = {
  hold: "HOLD",
  explore: "EXPLORE",
  recover: "RECOVER",
  reopen: "REOPEN",
  checkpoint: "CHECKPOINT",
  close: "CLOSE",
  stop: "STOP"
};
function controllerFromSteeringEntry(entry) {
  if (!isRec(entry) || typeof entry.decision !== "string") return null;
  const state = STEERING_DECISIONS[entry.decision];
  if (!state) return null;
  const to = isRec(entry.to) ? entry.to : null;
  const rung = to && isRung(to.rung) && to.rung !== "zero" && to.rung !== "ultra" ? to.rung : void 0;
  const from = isRec(entry.from) && typeof entry.from.rung === "string" ? entry.from.rung : null;
  const explanation = str(entry.explanation);
  return {
    kind: "reported",
    source: "steering-trace",
    state,
    ...rung ? { effective: rung } : {},
    ...from && explanation && entry.changed === true ? { transition: { from: from.toUpperCase(), to: state, reason: explanation } } : {}
  };
}
var PROPOSED_CONTROLLER_SCHEMA = "skill-heaven/controller-status@0";
function controllerFromCampaignStatus(value) {
  if (!isRec(value) || value.schema !== PROPOSED_CONTROLLER_SCHEMA) return null;
  const allowed = /* @__PURE__ */ new Set(["schema", "state", "effective", "progress", "transition"]);
  if (Object.keys(value).some((k) => !allowed.has(k))) return null;
  if (typeof value.state !== "string" || !/^[A-Z][A-Z0-9 ·_-]{0,31}$/.test(value.state)) return null;
  const out = { kind: "reported", source: "campaign", state: value.state };
  if (value.effective !== void 0) {
    if (!isRung(value.effective) || value.effective === "zero" || value.effective === "ultra") return null;
    out.effective = value.effective;
  }
  if (value.progress !== void 0) {
    const p = value.progress;
    if (!isRec(p) || !Number.isInteger(p.completed) || !Number.isInteger(p.total)) return null;
    const completed = p.completed;
    const total = p.total;
    if (completed < 0 || total < 1 || completed > total) return null;
    out.progress = { completed, total };
  }
  if (value.transition !== void 0) {
    const t = value.transition;
    if (!isRec(t) || typeof t.from !== "string" || typeof t.to !== "string" || typeof t.reason !== "string") return null;
    out.transition = { from: t.from, to: t.to, reason: t.reason };
  }
  return out;
}

// packages/status/src/compat.ts
var AGENT_PLUGIN_INSTALL = {
  posix: "curl -fsSL https://gaia-research.github.io/gaia-skill-heaven/install-agent-plugin.sh | sh",
  windows: "irm https://gaia-research.github.io/gaia-skill-heaven/install-agent-plugin.ps1 | iex",
  root: "$HOME/.local/share/gaia-skill-heaven-agent-plugin",
  marketplace: "$HOME/.local/share/gaia-skill-heaven-agent-plugin/marketplace",
  plugin: "$HOME/.local/share/gaia-skill-heaven-agent-plugin/marketplace/plugins/skill-heaven",
  uninstall: "$HOME/.local/share/gaia-skill-heaven-agent-plugin/uninstall.sh"
};
var LAUNCHER_INSTALL = {
  posix: "curl -fsSL https://gaia-research.github.io/gaia-skill-heaven/install.sh | sh",
  windows: "irm https://gaia-research.github.io/gaia-skill-heaven/install.ps1 | iex",
  uninstall: "$HOME/.local/share/gaia-skill-heaven/uninstall.sh"
};
var REPO = "https://github.com/gaia-research/gaia-skill-heaven/blob/main";
var HARNESS_PATHS = [
  {
    id: "claude",
    name: "Claude Code",
    bin: "claude",
    chip: "verified",
    probedVersion: "2.1.288",
    evidence: "Fresh-install receipt, 76/76 checks, GitHub main @ fdfd94e.",
    evidenceHref: `${REPO}/docs/RELEASE-ACCEPTANCE.md`,
    needsInstaller: false,
    commands: [
      "/plugin marketplace add gaia-research/gaia-skill-heaven",
      "/plugin install skill-heaven@gaia-skill-heaven"
    ],
    inHarness: true,
    blocked: null,
    update: "claude plugin marketplace update gaia-skill-heaven && claude plugin update skill-heaven@gaia-skill-heaven",
    remove: ["claude plugin uninstall skill-heaven@gaia-skill-heaven"],
    statusIntegration: "APPEND",
    statusNote: "The optional console (preview) adds a status entry beside yours \u2014 it never replaces your statusLine. Desktop paint needs a local probe.",
    launcher: "claude-zero"
  },
  {
    id: "codex",
    name: "Codex",
    bin: "codex",
    chip: "compatible",
    probedVersion: "0.146.0",
    evidence: "Live probe: plugin installed, five surfaces recognised, summon returned a card.",
    evidenceHref: `${REPO}/plugins/skill-heaven/PROBE.md`,
    needsInstaller: true,
    commands: [
      `codex plugin marketplace add "${AGENT_PLUGIN_INSTALL.marketplace}"`,
      "codex plugin add skill-heaven@gaia-skill-heaven"
    ],
    inHarness: false,
    blocked: null,
    update: "Re-run the installer, then reinstall in Codex \u2014 Codex keeps its own cached copy.",
    remove: ["codex plugin remove skill-heaven@gaia-skill-heaven", AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "UNSUPPORTED",
    statusNote: "Codex has no public status contribution API. Summon receipts still print in the transcript.",
    launcher: "codex-zero"
  },
  {
    id: "pi",
    name: "Pi",
    bin: "pi",
    chip: "compatible",
    probedVersion: "0.84.2",
    evidence: "Live probe of the Pi adapter. Pi 1.0.x now ships pi mcp; the adapter needs a re-probe there.",
    evidenceHref: `${REPO}/plugins/skill-heaven/dev.skill-heaven.pi/PROBE.md`,
    needsInstaller: true,
    commands: [`pi install "${AGENT_PLUGIN_INSTALL.plugin}" --approve`],
    inHarness: false,
    blocked: null,
    update: "Re-run the installer, then pi update.",
    remove: [`pi remove "${AGENT_PLUGIN_INSTALL.plugin}"`, AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "NATIVE SLOT",
    statusNote: "The pi-zero extension draws a widget; the canonical entropy line is not wired there yet.",
    launcher: "pi-zero"
  },
  {
    id: "grok",
    name: "Grok",
    bin: "grok",
    chip: "compatible",
    probedVersion: "1.0.5",
    evidence: "Live probe on 1.0.5; grok plugin validate also passes on 1.0.46 (static).",
    evidenceHref: `${REPO}/plugins/skill-heaven/PROBE.md`,
    needsInstaller: true,
    commands: [`grok plugin install "${AGENT_PLUGIN_INSTALL.plugin}" --trust`],
    inHarness: false,
    blocked: null,
    update: "Re-run the installer, then grok plugin update.",
    remove: ["grok plugin uninstall skill-heaven", AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "UNSUPPORTED",
    statusNote: "A command-backed status line is possible on Grok but not built.",
    launcher: "grok-zero"
  },
  {
    id: "hermes",
    name: "Hermes",
    bin: "hermes",
    chip: "compatible",
    probedVersion: "0.20.0",
    evidence: "Live probe: plugin installed and enabled, summon loaded a skill.",
    evidenceHref: `${REPO}/plugins/skill-heaven/PROBE.md`,
    needsInstaller: true,
    commands: [`hermes plugins install "file://${AGENT_PLUGIN_INSTALL.plugin}" --enable`],
    inHarness: false,
    blocked: null,
    update: "Re-run the installer, then reinstall in Hermes. Remove the Hermes registration with Hermes's own plugin manager.",
    // Hermes's own removal command was not verified on the machine that wrote
    // this table (its `--help` could not run), so none is printed.
    remove: [AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "UNSUPPORTED",
    statusNote: "Hermes has no stable public status contribution. Receipts print in the transcript.",
    launcher: "hermes-zero"
  },
  {
    id: "agy",
    name: "Antigravity",
    bin: "agy",
    chip: "partial",
    probedVersion: "1.3.1",
    evidence: "Static: agy plugin validate (1.3.1) loads the five skills and five commands but reports the MCP server as not found \u2014 /summon would have no tool. Needs a local probe.",
    evidenceHref: `${REPO}/docs/CONTROL-PLANE.md`,
    needsInstaller: false,
    commands: [],
    inHarness: false,
    blocked: "No registration command is printed until a logged-in probe shows Antigravity loading the summon server. The agy-zero launcher (probed on 1.2.13) gives a clean start meanwhile.",
    update: "Nothing to update \u2014 nothing is registered yet.",
    remove: [AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "UNSUPPORTED",
    statusNote: "A stacked status command is the target; not built.",
    launcher: "agy-zero"
  },
  {
    id: "other",
    name: "Another Agent Plugins client",
    bin: null,
    chip: "unverified",
    probedVersion: null,
    evidence: "The package follows Agent Plugins 1.0.0. Your client owns registration; it has not been probed here.",
    evidenceHref: "https://agent-plugins.org/specification",
    needsInstaller: true,
    commands: [],
    inHarness: false,
    blocked: `Point your client's own plugin install at ${AGENT_PLUGIN_INSTALL.plugin}. There is no universal registration command.`,
    update: "Re-run the installer; your client may keep its own cached copy.",
    remove: [AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "UNSUPPORTED",
    statusNote: "Depends on your client.",
    launcher: null
  }
];
var CHIP_LABEL = {
  verified: "Verified",
  compatible: "Compatible",
  partial: "Partial",
  unverified: "Unverified",
  "needs-local-probe": "Needs local probe"
};
var CHIP_MEANING = {
  verified: "A fresh install was verified end to end on the pinned version.",
  compatible: "A live probe passed on the pinned version. Yours may differ.",
  partial: "Part of the plugin loads; something is proven missing.",
  unverified: "Not probed. The package is portable; this client is untested.",
  "needs-local-probe": "Could not be established without a logged-in session."
};
function harnessById(id) {
  const found = HARNESS_PATHS.find((h) => h.id === id);
  if (!found) throw new Error(`unknown harness ${id}`);
  return found;
}
export {
  AGENT_PLUGIN_INSTALL,
  CHIP_LABEL,
  CHIP_MEANING,
  CLOSE_CALL_MARGIN,
  DEFAULT_FIELD_LIMIT,
  GROUND_HEX,
  HARNESS_PATHS,
  LAUNCHER_INSTALL,
  PROPOSED_CONTROLLER_SCHEMA,
  ROLE_COLORS,
  RUNGS,
  RUNG_BAND,
  bandOf,
  cellWidth,
  controllerFromCampaignStatus,
  controllerFromSteeringEntry,
  controllerSegments,
  describeEvent,
  describeReading,
  describeStatus,
  directionFromSurface,
  emptyStatus,
  eventFromSummonResult,
  eventLines,
  formatMs,
  formatScore,
  harnessById,
  isRung,
  markRead,
  noticeLines,
  paintAnsi,
  readingFromProfileManifest,
  readingRung,
  readingToken,
  reduceStatus,
  renderStatusSegments,
  resolveColorDepth,
  sanitizeDisplay,
  segmentsWidth,
  selectionFromCommand,
  skillsFromSessionManifest,
  statusLevels,
  toPlain,
  withReading
};
