// @ts-nocheck — generated from type-checked source.
// GENERATED by scripts/build-console.mjs — do not edit.
// packages/console/extension/console.ts
import { resolve } from "node:path";

// packages/status/src/model.ts
var RUNGS = ["zero", "low", "med", "high", "xhigh", "max", "ultra"];
var RUNG_BAND = Object.freeze({
  zero: "zero",
  low: "heaven",
  med: "heaven",
  high: "hell",
  xhigh: "hell",
  max: "hell",
  ultra: "ultra"
});
function readingRung(reading) {
  if (reading.kind === "selected") return reading.rung;
  if (reading.kind === "boot" && reading.posture === "product-floor") return "zero";
  return null;
}
function isRung(value) {
  return typeof value === "string" && RUNGS.includes(value);
}
function emptyStatus() {
  return {
    reading: { kind: "unknown" },
    skills: null,
    summons: null,
    lastArrival: null,
    controller: { kind: "not-selected" },
    summonTool: "unknown"
  };
}

// packages/status/src/sanitize.ts
var ANSI = /\u001b(?:\[[0-?]*[ -/]*[@-~]|\][^\u0007\u001b]*(?:\u0007|\u001b\\)|[@-Z\\-_])/g;
var CONTROLS = /[\u0000-\u001f\u007f-\u009f]/g;
var BIDI = /[‎‏‪-‮⁦-⁩]/g;
var RESERVED = /* @__PURE__ */ new Map([
  ["\u25C7", "*"],
  ["\u25C6", "*"],
  ["\u2039", "<"],
  ["\u203A", ">"],
  ["\xD7", "x"]
]);
var DEFAULT_FIELD_LIMIT = 48;
function sanitizeDisplay(value, limit = DEFAULT_FIELD_LIMIT) {
  if (value === null || value === void 0) return "";
  let text = String(value).replace(ANSI, "").replace(BIDI, "").replace(CONTROLS, " ");
  let out = "";
  for (const ch of text) out += RESERVED.get(ch) ?? ch;
  text = out.replace(/\s+/g, " ").trim();
  const chars = Array.from(text);
  if (limit > 0 && chars.length > limit) return chars.slice(0, Math.max(1, limit - 1)).join("") + "\u2026";
  return text;
}
function cellWidth(text) {
  let width = 0;
  for (const ch of text) {
    const code = ch.codePointAt(0) ?? 0;
    width += isWide(code) ? 2 : 1;
  }
  return width;
}
function isWide(code) {
  return code >= 4352 && code <= 4447 || code >= 11904 && code <= 42191 || code >= 44032 && code <= 55203 || code >= 63744 && code <= 64255 || code >= 65072 && code <= 65103 || code >= 65280 && code <= 65376 || code >= 65504 && code <= 65510 || code >= 127744 && code <= 129791 || code >= 131072 && code <= 262141;
}

// packages/status/src/tokens.ts
var ROLE_COLORS = Object.freeze({
  umbrella: { hex: "#a58ae0", ansi256: 141, ansi16: 35, cssVar: "--sh-violet" },
  ultra: { hex: "#d9b25c", ansi256: 179, ansi16: 33, cssVar: "--sh-ultra" },
  zero: { hex: "#5fc2d6", ansi256: 80, ansi16: 36, cssVar: "--sh-zero" },
  heaven: { hex: "#6f96d8", ansi256: 68, ansi16: 34, cssVar: "--sh-heaven" },
  hell: { hex: "#e094c8", ansi256: 175, ansi16: 95, cssVar: "--sh-hell" },
  ink: { hex: "#eeebe6", ansi256: 255, ansi16: 39, cssVar: "--sh-bone" },
  dim: { hex: "#9a9691", ansi256: 246, ansi16: 90, cssVar: "--sh-dim" },
  arbor: { hex: "#55c878", ansi256: 77, ansi16: 32, cssVar: "--sh-arbor" },
  stop: { hex: "#c81e1e", ansi256: 160, ansi16: 31, cssVar: "--sh-stop" },
  amber: { hex: "#e0b45c", ansi256: 179, ansi16: 33, cssVar: "--sh-amber" }
});

// packages/status/src/render.ts
var SEP = { text: " \xB7 ", role: "dim" };
var seg = (text, role) => ({ text, role });
function readingToken(reading) {
  switch (reading.kind) {
    case "selected":
      return reading.rung.toUpperCase();
    case "boot":
      return reading.posture === "product-floor" ? "ZERO" : reading.posture === "curated" ? "CURATED" : "NATIVE";
    case "native":
      return "NATIVE";
    case "unknown":
      return "?";
  }
}
function readingRole(reading) {
  const rung = readingRung(reading);
  if (!rung) return "ink";
  const band = RUNG_BAND[rung];
  return band === "zero" ? "zero" : band === "heaven" ? "heaven" : band === "hell" ? "hell" : "ultra";
}
function isUltra(status) {
  return readingRung(status.reading) === "ultra";
}
function skillsText(n, short) {
  if (n === null) return short ? "?" : "? skills";
  if (short) return String(n);
  return `${n} ${n === 1 ? "skill" : "skills"}`;
}
function readingSegments(status) {
  return [
    seg("\u2039\u2039", "heaven"),
    seg(" ", "dim"),
    seg(`[${readingToken(status.reading)}]`, readingRole(status.reading)),
    seg(" ", "dim"),
    seg("\u203A\u203A", "hell")
  ];
}
function headSegments(status, withWord) {
  const ultra = isUltra(status);
  const out = [];
  if (status.fixture || status.controller.kind === "fixture") out.push(seg("FIXTURE", "amber"), seg(" ", "dim"));
  out.push(seg(ultra ? "\u25C6" : "\u25C7", ultra ? "ultra" : "umbrella"));
  if (withWord) out.push(seg(" entropy", "umbrella"));
  out.push(seg(" ", "dim"), ...readingSegments(status));
  return out;
}
function controllerSegments(controller, opts = { progress: true }) {
  switch (controller.kind) {
    case "not-selected":
      return [];
    case "unavailable":
      return [SEP, seg("controller unavailable", "dim")];
    case "reported":
    case "fixture": {
      const out = [SEP, seg(sanitizeDisplay(controller.state, 24).toUpperCase(), "ultra")];
      if (controller.effective) {
        const band = RUNG_BAND[controller.effective];
        const role = band === "heaven" ? "heaven" : "hell";
        out.push(SEP, seg("now ", "dim"), seg(controller.effective.toUpperCase(), role), seg(band === "heaven" ? " \u2039" : " \u203A", role));
      }
      if (opts.progress && controller.progress) {
        out.push(SEP, seg(`${controller.progress.completed}/${controller.progress.total}`, "ink"));
      }
      return out;
    }
  }
}
function statusLevels(status, mode) {
  if (mode === "off") return [];
  const ultra = isUltra(status);
  const controller = ultra ? status.controller : { kind: "not-selected" };
  const skills = [SEP, seg(skillsText(status.skills, false), "ink")];
  const summons = status.summons === null ? [] : [seg(" / ", "dim"), seg(`${status.summons} ${status.summons === 1 ? "summon" : "summons"}`, "dim")];
  const arrival = status.lastArrival ? [SEP, seg(`+${sanitizeDisplay(status.lastArrival, 32)}`, "ink")] : [];
  const full = [
    [...headSegments(status, true), ...skills, ...summons, ...controllerSegments(controller), ...arrival],
    [...headSegments(status, true), ...skills, ...summons, ...controllerSegments(controller)],
    [...headSegments(status, true), ...skills, ...controllerSegments(controller)],
    [...headSegments(status, true), ...skills, ...controllerSegments(controller, { progress: false })]
  ];
  const compact = [
    [...headSegments(status, true), ...skills],
    [...headSegments(status, false), SEP, seg(skillsText(status.skills, true), "ink")],
    [...headSegments(status, false)]
  ];
  const bare = [];
  if (status.fixture || status.controller.kind === "fixture") bare.push(seg("FIXTURE", "amber"), seg(" ", "dim"));
  bare.push(seg(`[${readingToken(status.reading)}]`, readingRole(status.reading)));
  return mode === "full" ? [...full, ...compact, bare] : [...compact, bare];
}
function segmentsWidth(segments) {
  return segments.reduce((sum, s) => sum + cellWidth(s.text), 0);
}
function renderStatusSegments(status, mode, width) {
  const levels = statusLevels(status, mode);
  if (levels.length === 0) return [];
  if (width === void 0 || !Number.isFinite(width)) return levels[0];
  return levels.find((level) => segmentsWidth(level) <= width) ?? levels[levels.length - 1];
}
function directionGlyph(direction) {
  if (direction === "converge") return seg("\u2039", "heaven");
  if (direction === "explore") return seg("\u203A", "hell");
  return seg("\u25C7", "umbrella");
}
function formatScore(value) {
  if (value === null || !Number.isFinite(value)) return null;
  const clamped = Math.max(0, Math.min(1, value));
  return clamped >= 1 ? "1.00" : clamped.toFixed(2).replace(/^0/, "");
}
function formatMs(ms) {
  if (ms === null || !Number.isFinite(ms) || ms < 0) return null;
  return ms < 1e3 ? `${Math.round(ms)}ms` : `${(ms / 1e3).toFixed(2)}s`;
}
var CLOSE_CALL_MARGIN = 0.1;
function receiptDetail(skill, delta) {
  const parts = [];
  if (skill.matchKind !== "unknown") parts.push(skill.matchKind);
  const score = formatScore(skill.score);
  if (score) parts.push(score);
  const margin = formatScore(skill.margin);
  if (margin) parts.push(`\u0394 ${margin}`);
  if (skill.cache !== "unknown") parts.push(skill.cache);
  const ms = formatMs(skill.ms);
  if (ms) parts.push(ms);
  if (delta !== null) parts.push(`+${delta}`);
  return [seg("  ", "dim"), seg(parts.join(" \xB7 ") || "no ranking disclosure", "dim")];
}
function eventLines(event) {
  const lines = eventLinesInner(event);
  if (event.evidence === "fixture" && lines[0]) lines[0] = [seg("FIXTURE", "amber"), seg(" ", "dim"), ...lines[0]];
  return lines;
}
function eventLinesInner(event) {
  switch (event.kind) {
    case "summoned": {
      const [first, ...rest] = event.skills;
      const line1 = [directionGlyph(event.direction), seg(" summoned  ", "dim")];
      line1.push(seg(first ? sanitizeDisplay(first.name, 40) : "nothing", "ink"));
      if (rest.length > 0) line1.push(seg(` +${rest.length} more`, "dim"));
      const line2 = first ? receiptDetail(first, event.delta) : [seg("  ", "dim"), seg("no skill in result", "dim")];
      if (event.sourceHealth.kind === "stale") line2.push(SEP, seg("? index stale", "amber"));
      return [line1, line2];
    }
    case "previewed": {
      const [first] = event.skills;
      const line1 = [seg("\u25C7", "umbrella"), seg(" lens  ", "dim")];
      if (event.skills.length === 1 && first) line1.push(seg(sanitizeDisplay(first.name, 40), "ink"));
      else line1.push(seg(`${event.skills.length} candidates`, "ink"));
      const parts = [seg("  ", "dim"), seg("nothing materialized", "dim")];
      if (first && event.skills.length > 1) parts.push(SEP, seg(`top ${sanitizeDisplay(first.name, 32)}`, "dim"));
      if (first?.margin !== null && first?.margin !== void 0 && first.margin < CLOSE_CALL_MARGIN && event.skills.length > 1) {
        parts.push(SEP, seg(`\u0394 ${formatScore(first.margin)} close call (retrieval)`, "dim"));
      }
      return [line1, parts];
    }
    case "no-match": {
      const detail = event.considered === null ? "0 admitted" : `${event.considered} considered \xB7 0 admitted`;
      const reason = event.reason ? ` \xB7 ${sanitizeDisplay(event.reason, 60)}` : "";
      const tail = event.preview ? " \xB7 nothing materialized" : "";
      return [
        [seg("\u25C7", "umbrella"), seg(event.preview ? " lens  " : " summon  ", "dim"), seg("\xD7", "ink"), seg(" no match", "ink")],
        [seg("  ", "dim"), seg(detail + reason + tail, "dim")]
      ];
    }
    case "unavailable":
      return [
        [seg("\u25C7", "umbrella"), seg(" summon  ", "dim"), seg("?", "amber"), seg(" unavailable", "ink")],
        [seg("  ", "dim"), seg(sanitizeDisplay(event.reason, 72), "dim")]
      ];
    case "error":
      return [
        [seg("\u25C7", "umbrella"), seg(" summon  ", "dim"), seg("!", "stop"), seg(" failed", "ink")],
        [seg("  ", "dim"), seg(sanitizeDisplay(event.reason, 72), "dim")]
      ];
  }
}
function noticeLines(notice) {
  if (notice.kind === "looking") {
    return [
      [seg("\u25C7", "umbrella"), seg(" lens  ", "dim"), seg("looking\u2026", "ink")],
      [seg("  ", "dim"), seg(`${sanitizeDisplay(notice.query, 48)} \xB7 nothing materialized`, "dim")]
    ];
  }
  return [
    [seg("\u25C7", "umbrella"), seg(" summon  ", "dim"), seg("?", "amber"), seg(" not connected", "ink")],
    [seg("  ", "dim"), seg("the summon tool is not available in this session", "dim")]
  ];
}
function sgr(role, depth) {
  const c = ROLE_COLORS[role];
  if (depth === "truecolor") {
    const n = parseInt(c.hex.slice(1), 16);
    return `\x1B[38;2;${n >> 16 & 255};${n >> 8 & 255};${n & 255}m`;
  }
  if (depth === "256") return `\x1B[38;5;${c.ansi256}m`;
  return `\x1B[${c.ansi16}m`;
}
function paintAnsi(segments, depth) {
  if (depth === "none") return toPlain(segments);
  return segments.map((s) => s.role === "dim" && s.text.trim() === "" ? s.text : `${sgr(s.role, depth)}${s.text}\x1B[39m`).join("");
}
function toPlain(segments) {
  return segments.map((s) => s.text).join("");
}

// packages/status/src/adapters.ts
var isRec = (v) => typeof v === "object" && v !== null && !Array.isArray(v);
var str = (v) => typeof v === "string" && v.length > 0 ? v : null;
var num = (v) => typeof v === "number" && Number.isFinite(v) ? v : null;
var BAND_COMMANDS = [
  { command: "skill-zero", rungs: ["zero"], fallback: "zero" },
  { command: "skill-heaven", rungs: ["low", "med"], fallback: "low" },
  { command: "skill-hell", rungs: ["high", "xhigh", "max"], fallback: "high" },
  { command: "skill-ultra", rungs: ["ultra"], fallback: "ultra" }
];
function selectionFromCommand(text) {
  const match = /^\s*\/(?:[a-z0-9-]+:)?(skill-zero|skill-heaven|skill-hell|skill-ultra)(?:\s+(\S+))?\s*$/i.exec(text);
  if (!match) return null;
  const entry = BAND_COMMANDS.find((b) => b.command === match[1].toLowerCase());
  const arg = match[2]?.toLowerCase();
  if (!arg) return { kind: "selected", rung: entry.fallback, source: "observed-command" };
  if (entry.command === "skill-zero") return arg === "all" ? { kind: "selected", rung: "zero", source: "observed-command" } : null;
  if (isRung(arg) && entry.rungs.includes(arg)) return { kind: "selected", rung: arg, source: "observed-command" };
  return null;
}
function withReading(status, reading) {
  const ultra = reading.kind === "selected" && reading.rung === "ultra";
  const boot = status.boot ?? (status.reading.kind === "selected" || status.reading.kind === "unknown" ? void 0 : status.reading);
  const controller = ultra ? status.controller.kind === "reported" ? status.controller : { kind: "unavailable" } : { kind: "not-selected" };
  return { ...status, reading, controller, ...boot ? { boot } : {} };
}
function directionFromSurface(surface) {
  if (surface === "any") return "manual";
  if (surface === "heaven") return "converge";
  if (surface === "hell") return "explore";
  return "unspecified";
}
function laneOf(skill) {
  if (skill.invocation === "human") return "human-led";
  if (skill.invocation === "model") return "model-led";
  if (skill.invocation === "any") return "unspecified";
  return "unknown";
}
function receiptFrom(skill, stage, agent) {
  const retrieval = isRec(skill.retrieval) ? skill.retrieval : {};
  const matchKind = retrieval.matchKind === "exact" || retrieval.matchKind === "ranked" ? retrieval.matchKind : "unknown";
  const cacheRaw = skill.cacheState ?? skill.cache;
  const totalSeconds = num(skill.totalSeconds);
  const installability = isRec(skill.installability) ? str(skill.installability.state) ?? "unknown" : "unknown";
  return {
    id: str(skill.id) ?? "unknown",
    name: str(skill.name) ?? str(skill.id) ?? "unknown",
    stage,
    matchKind,
    score: num(retrieval.score) ?? num(skill.score),
    margin: num(retrieval.margin) ?? num(skill.margin),
    cache: cacheRaw === "cold" || cacheRaw === "warm" ? cacheRaw : "unknown",
    ms: totalSeconds === null ? null : Math.round(totalSeconds * 1e3),
    lane: laneOf(skill),
    source: str(skill.source),
    repoUrl: str(skill.repoUrl),
    ref: str(skill.branch),
    sourceUrl: str(skill.sourceUrl),
    subpath: str(skill.subpath),
    sha256: str(skill.sha256),
    path: str(skill.path),
    installability,
    agent
  };
}
function sourceHealthOf(result) {
  const ranking = isRec(result.ranking) ? result.ranking : null;
  if (!ranking || typeof ranking.stale !== "boolean") return { kind: "unknown" };
  const age = num(ranking.indexAgeDays);
  const indexAgeDays = age === null ? null : Math.floor(age);
  return ranking.stale ? { kind: "stale", indexAgeDays } : { kind: "fresh", indexAgeDays };
}
function arborOf(result, summoned) {
  const arbor = isRec(result.arbor) ? result.arbor : null;
  if (!arbor) return "unknown";
  if (arbor.publicationState === "unavailable" || arbor.publicationState === "unreadable") return "unavailable";
  if (arbor.publicationState !== "loaded") return "unknown";
  return summoned.some((s) => isRec(s.arbor) && s.arbor.join === "content-pinned") ? "governed-record" : "no-record";
}
var NO_MATCH_REASON = {
  no_candidates: "no candidates in the source",
  below_floor: "nothing cleared the relevance floor",
  all_filtered: "every candidate was outside this lane"
};
function eventFromSummonResult(structured, call = {}, failure) {
  const at = call.at ?? null;
  const agent = call.agent ?? null;
  if (failure?.isError) {
    const text = failure.text ?? "the summon tool reported an error";
    const unavailable = /unresolvable|unreachable|ENOTFOUND|EAI_AGAIN|fetch failed|network|offline/i.test(text);
    return {
      kind: unavailable ? "unavailable" : "error",
      direction: "unspecified",
      query: call.query ?? "",
      preview: call.preview === true,
      reason: text,
      at,
      evidence: "observed"
    };
  }
  if (!isRec(structured)) {
    return {
      kind: "error",
      direction: "unspecified",
      query: call.query ?? "",
      preview: call.preview === true,
      reason: "the summon result had no structured content",
      at,
      evidence: "observed"
    };
  }
  const direction = directionFromSurface(structured.surface);
  const query = str(structured.query) ?? call.query ?? "";
  const sourceHealth = sourceHealthOf(structured);
  if (structured.noMatch !== null && structured.noMatch !== void 0) {
    const noMatch = isRec(structured.noMatch) ? structured.noMatch : {};
    const reason = typeof noMatch.reason === "string" ? NO_MATCH_REASON[noMatch.reason] ?? null : null;
    return { kind: "no-match", direction, query, preview: call.preview === true, considered: null, reason, at, evidence: "reported", sourceHealth };
  }
  const summoned = Array.isArray(structured.summoned) ? structured.summoned.filter(isRec) : [];
  const previewed = Array.isArray(structured.previewed) ? structured.previewed.filter(isRec) : [];
  if (summoned.length === 0 && (previewed.length > 0 || call.preview === true)) {
    return {
      kind: "previewed",
      direction,
      query,
      skills: previewed.map((s) => receiptFrom(s, "previewed", agent)),
      delta: 0,
      preview: true,
      at,
      evidence: "reported",
      sourceHealth
    };
  }
  const skipped = Array.isArray(structured.skipped) ? structured.skipped : [];
  if (summoned.length === 0 && skipped.length > 0) {
    const first = skipped[0];
    const why = isRec(first) ? str(first.why) ?? str(first.reason) ?? str(first.error) : str(first);
    return {
      kind: "error",
      direction,
      query,
      preview: call.preview === true,
      reason: why ? `nothing materialized: ${why}` : "nothing materialized: every candidate was skipped",
      at,
      evidence: "reported"
    };
  }
  const composition = isRec(structured.composition) && structured.composition.mode === "relevance-only" ? "relevance-only" : "unknown";
  return {
    kind: "summoned",
    direction,
    query,
    skills: summoned.map((s) => receiptFrom(s, "materialized", agent)),
    delta: summoned.length,
    preview: false,
    at,
    evidence: "reported",
    composition,
    arbor: arborOf(structured, summoned),
    sourceHealth
  };
}
function reduceStatus(status, event) {
  if (event.kind === "previewed" || event.kind !== "summoned" && event.preview) return status;
  const summons = status.summons === null ? null : status.summons + 1;
  if (event.kind !== "summoned") return { ...status, summons };
  const skills = status.skills === null ? null : status.skills + event.delta;
  const last = event.skills[event.skills.length - 1];
  return { ...status, skills, summons, lastArrival: last ? last.name : status.lastArrival };
}
function markRead(event, readPath) {
  if (event.kind !== "summoned") return event;
  const norm = readPath.replace(/\\/g, "/");
  let changed = false;
  const skills = event.skills.map((s) => {
    if (!s.path || s.stage === "in-context") return s;
    let root = s.path.replace(/\\/g, "/");
    while (root.endsWith("/")) root = root.slice(0, -1);
    if (norm === `${root}/SKILL.md`) {
      changed = true;
      return { ...s, stage: "in-context" };
    }
    return s;
  });
  return changed ? { ...event, skills } : event;
}

// packages/status/src/compat-console.ts
var step = (argv, run, effect) => ({ where: "shell", argv, run, effect });
var piece = (register, update, remove) => ({ register, update, remove });
var degraded = (via, note) => ({ level: "degraded", via, note });
var ROOT = "https://github.com/gaia-research/gaia-skill-heaven/blob/main";
function adapterPath(id) {
  const pi = id === "pi";
  const hermes = id === "hermes";
  const agy = id === "agy";
  const versions = { pi: "1.0.4", codex: "0.161.0", hermes: "0.20.0", grok: "1.0.46", agy: "1.3.1" };
  const register = (console2) => {
    const dir = console2 ? "{{CONSOLE_DIR}}" : "{{PLUGIN_DIR}}";
    const name = console2 ? "skill-heaven-console" : "skill-heaven";
    if (pi) return [step(["pi", "install", dir, "--approve"], `pi install "${dir}" --approve`, `registers only ${name} as a Pi package`)];
    if (id === "codex") return [
      ...console2 ? [] : [step(["codex", "plugin", "marketplace", "add", "{{MARKETPLACE_DIR}}"], 'codex plugin marketplace add "{{MARKETPLACE_DIR}}"', "registers the staged marketplace")],
      step(["codex", "plugin", "add", `${name}@gaia-skill-heaven`], `codex plugin add ${name}@gaia-skill-heaven`, `registers only ${name}`)
    ];
    if (hermes) return [step(["hermes", "plugins", "install", `file://${dir}`, "--enable"], `hermes plugins install "file://${dir}" --enable`, `registers ${name}; staging MUST supply an independent Git root (Hermes clones Git sources)`)];
    if (id === "grok") return [step(["grok", "plugin", "install", dir, "--trust"], `grok plugin install "${dir}" --trust`, `registers only ${name}`)];
    return [step(["agy", "plugin", "install", dir], `agy plugin install "${dir}"`, `registers only ${name}; real HOME required`)];
  };
  const remove = (console2) => {
    const name = console2 ? "skill-heaven-console" : "skill-heaven";
    const dir = console2 ? "{{CONSOLE_DIR}}" : "{{PLUGIN_DIR}}";
    if (pi) return [step(["pi", "remove", dir], `pi remove "${dir}"`, `removes only ${name}`)];
    if (id === "codex") return [step(["codex", "plugin", "remove", `${name}@gaia-skill-heaven`], `codex plugin remove ${name}@gaia-skill-heaven`, `removes only ${name}`)];
    if (hermes) return [
      step(["hermes", "plugins", "disable", name], `hermes plugins disable ${name}`, `disables only ${name}; preserves the host-owned deny-list`),
      step(["hermes", "plugins", "remove", name], `hermes plugins remove ${name}`, `removes only ${name}'s cached plugin directory`)
    ];
    if (agy) return [{ ...step(["agy", "plugin", "uninstall", name], `agy plugin uninstall ${name}`, `uninstalls only ${name}; real HOME preserved`), stdin: "y\n" }];
    return [step(["grok", "plugin", "uninstall", name], `grok plugin uninstall ${name}`, `removes only ${name}`)];
  };
  const update = (console2) => {
    if (pi) return [];
    if (hermes) {
      const steps = register(console2);
      return steps.map((s) => ({ ...s, argv: [...s.argv, "--force"], run: s.run + " --force", effect: s.effect + "; replaces this cached copy" }));
    }
    if (agy) return register(console2);
    if (id === "codex") return [...remove(console2), ...register(console2)];
    return [...remove(console2), ...register(console2)];
  };
  const command = agy ? "/skill-heaven-console:heaven" : "/heaven";
  const report = pi ? "ctx.ui.setWidget (own key, below editor)" : hermes ? "native register_command /heaven report" : "explicit console skill/command (model-mediated)";
  const console = {
    kind: pi ? "extension-ui" : "command-backed",
    mechanism: pi ? "Separate Pi extension: own setStatus key and command-opened widget. /lens drafts a preview handoff; /heaven fill prefills only, a human submits through normal tool approval." : `${report}; one canonical renderConsoleText report, no fake HUD or status configuration rewrite.`,
    command,
    commandPrefix: agy ? "skill-heaven:" : "",
    surfaces: {
      status: pi ? { level: "native", via: "ctx.ui.setStatus(skill-heaven-console)", note: "Appends an owned entry; does not replace the footer." } : degraded(report, "Report only, not a persistent status contribution."),
      lens: degraded(pi ? "/lens + /heaven fill" : hermes ? "/lens (printed draft)" : `${command} lens`, pi || hermes ? "Draft only: no tool call, retrieval or materialization until a human submits the handoff through normal host tool approval. Observed preview results use the same shared model." : "Explicit model-mediated preview:true on the existing Core tool; printed handoff, no automatic tool call."),
      session: degraded(report, "Bounded receipt window. Exact session binding required; no newest-directory guess."),
      scope: degraded(report, "Printed controls, not enforcement. Ultra controller remains unavailable."),
      flow: { level: "unsupported", via: report, note: "No implemented, empirically pinned agent-id attribution. Summons attributed to main; no invented agents." },
      trust: degraded(report, "Lists capabilities and limits; does not rate them.")
    },
    observes: { summon: pi ? "observed" : "reported", read: pi ? "observed" : "unavailable", agents: "unavailable", rung: pi ? "observed" : "unavailable" },
    summonTools: pi ? ["summon"] : agy ? ["skill-heaven_skill-summon/summon"] : id === "codex" ? ["mcp__skill-summon__summon"] : [],
    trust: [
      { id: "skill-heaven", profile: "core", kind: "harness runtime package", version: "0.1.2", summary: "Five entropy surfaces and the bundled summon engine.", reads: ["configured skill source"], writes: ["disposable engine session directory"], network: "Core fetches the configured skill source", disable: remove(false)[0].run },
      { id: "skill-heaven-console", profile: "full", kind: pi ? "Pi extension package" : hermes ? "Hermes native Python plugin + Node painter" : "command/skill plugin + Node report", version: "0.1.0", summary: "Read-only projection of the shared console model; independently removable.", reads: pi ? ["exact Core summon results", "successful read events", "active session branch"] : hermes ? ["caller-supplied exact Core sessionRoot ledger"] : ["caller-supplied exact Core sessionRoot ledger", ...agy ? ["optional exact conversation transcript and confined result files"] : []], writes: [], network: pi || hermes ? "none; Lens only drafts a handoff, normal Core calls remain subject to host approval" : "none of its own; explicit model-mediated Lens requests use the existing Core tool", disable: remove(true)[0].run, notes: ["No hidden submission, automatic materialization, daemon, global configuration rewrite or independent summon server.", ...pi ? ["Restored branches cannot prove successful body reads or rung selection; those facts are not replayed."] : ["Without an exact binding, counts are unknown. Command/skill output may pass through the model."]] }
    ],
    probe: { version: versions[id], summary: `Saved ${versions[id]} API/layout evidence informed this adapter. Compiled artifact and synthetic conformance tests are NOT an empirical Full compatibility receipt; live install, Lens and console-only removal still need a probe.`, href: `${ROOT}/plugins/skill-heaven-console-${id}/README.md` }
  };
  return { console, core: piece(register(false), update(false), remove(false)), consolePiece: piece(register(true), update(true), remove(true)), fullBlocked: null };
}

// packages/status/src/compat.ts
var AGENT_PLUGIN_INSTALL = {
  posix: "curl -fsSL https://gaia-research.github.io/gaia-skill-heaven/install-agent-plugin.sh | sh",
  windows: "irm https://gaia-research.github.io/gaia-skill-heaven/install-agent-plugin.ps1 | iex",
  root: "$HOME/.local/share/gaia-skill-heaven-agent-plugin",
  marketplace: "$HOME/.local/share/gaia-skill-heaven-agent-plugin/marketplace",
  plugin: "$HOME/.local/share/gaia-skill-heaven-agent-plugin/marketplace/plugins/skill-heaven",
  uninstall: "$HOME/.local/share/gaia-skill-heaven-agent-plugin/uninstall.sh"
};
var PENDING = (name) => ({
  console: {
    kind: "command-backed",
    mechanism: `pending recon for ${name}`,
    command: null,
    commandPrefix: "",
    surfaces: {
      status: { level: "unsupported", via: "pending", note: "pending" },
      lens: { level: "unsupported", via: "pending", note: "pending" },
      session: { level: "unsupported", via: "pending", note: "pending" },
      scope: { level: "unsupported", via: "pending", note: "pending" },
      flow: { level: "unsupported", via: "pending", note: "pending" },
      trust: { level: "unsupported", via: "pending", note: "pending" }
    },
    observes: { summon: "unavailable", read: "unavailable", agents: "unavailable", rung: "unavailable" },
    summonTools: [],
    trust: [],
    probe: { version: null, summary: "pending", href: null }
  },
  core: { register: [], update: [], remove: [] },
  consolePiece: null,
  fullBlocked: "pending recon"
});
var REPO = "https://github.com/gaia-research/gaia-skill-heaven/blob/main";
var HARNESS_PATHS = [
  {
    id: "claude",
    name: "Claude Code",
    bin: "claude",
    chip: "verified",
    probedVersion: "2.1.288",
    evidence: "Fresh-install receipt, 76/76 checks, GitHub main @ fdfd94e.",
    evidenceHref: `${REPO}/docs/RELEASE-ACCEPTANCE.md`,
    needsInstaller: false,
    commands: [
      "/plugin marketplace add gaia-research/gaia-skill-heaven",
      "/plugin install skill-heaven@gaia-skill-heaven"
    ],
    inHarness: true,
    blocked: null,
    update: "claude plugin marketplace update gaia-skill-heaven && claude plugin update skill-heaven@gaia-skill-heaven",
    remove: ["claude plugin uninstall skill-heaven@gaia-skill-heaven"],
    statusIntegration: "APPEND",
    statusNote: "The optional console (preview) adds a status entry beside yours \u2014 it never replaces your statusLine. Probed live in the terminal on 2.1.294; its desktop paint is not probed.",
    launcher: "claude-zero",
    // 2.1.294 refuses a bare /summon: it resolves to the portable skill, which is user-invocable: false.
    firstRun: "/skill-heaven:summon <what you need>",
    console: {
      kind: "pane",
      mechanism: "Claude Code's Mods API (function hooks, early access since 2.1.293): $.ui.status appends a status entry beside your own, an AbovePrompt band carries Lens, and /heaven opens a pane with Session, Scope, Flow and Trust.",
      command: "/heaven",
      commandPrefix: "skill-heaven:",
      surfaces: {
        status: { level: "native", via: "$.ui.status (APPEND \u2014 never touches statusLine)", note: "Probed live in the terminal on 2.1.294; desktop paint is not probed." },
        lens: { level: "native", via: "AbovePrompt band + $.prompt.fill", note: "A button only pre-fills the prompt; you press Enter." },
        session: { level: "native", via: "the /heaven pane", note: "Every field carries an evidence class." },
        scope: { level: "native", via: "the /heaven pane", note: "Rung controls pre-fill commands; nothing runs until you submit." },
        flow: { level: "native", via: "agentId on tool.call and turn.complete", note: "Only agents the host reported appear." },
        trust: { level: "native", via: "the /heaven pane", note: "Lists what the console reads and writes; it does not rate it." }
      },
      observes: { summon: "observed", read: "observed", agents: "observed", rung: "observed" },
      summonTools: ["mcp__plugin_skill-heaven_skill-summon__summon", "mcp__skill-summon__summon"],
      trust: [
        {
          id: "skill-heaven",
          profile: "core",
          kind: "Claude Code plugin",
          version: "0.1.2",
          summary: "The runtime: five commands and one bundled MCP server (skill-summon).",
          reads: ["the skill source you configure (network, by the summon tool)"],
          writes: ["a disposable session directory under your temp dir"],
          network: "the summon tool fetches the skill source",
          disable: "claude plugin uninstall skill-heaven@gaia-skill-heaven"
        },
        {
          id: "skill-heaven-console",
          profile: "full",
          kind: "Claude Code plugin (Mods, preview)",
          version: "0.1.0",
          summary: "The console: a status entry, the Lens band and the /heaven pane. Runs inside Claude Code as local code.",
          notes: ["/lens and /heaven print a one-line result that the model can read. It is fixed text and carries nothing a skill source supplied."],
          reads: ["summon tool results", "your /skill-* commands", "Read and Agent tool calls \u2014 to observe, never to change"],
          writes: ["nothing to disk", "session-only $.state"],
          network: "none of its own; /lens calls the bundled summon tool, which fetches the skill source",
          disable: "claude plugin uninstall skill-heaven-console@gaia-skill-heaven"
        }
      ],
      probe: {
        version: "2.1.294",
        summary: "the console was probed live in the terminal on 2.1.294; desktop paint is not probed",
        href: `${REPO}/plugins/skill-heaven-console/README.md`
      }
    },
    core: {
      register: [
        { where: "shell", run: 'claude plugin marketplace add "{{MARKETPLACE_DIR}}"', argv: ["claude", "plugin", "marketplace", "add", "{{MARKETPLACE_DIR}}"], effect: "adds the reviewed staged local marketplace to Claude Code's plugin registry" },
        { where: "harness", run: "/plugin install skill-heaven@gaia-skill-heaven", shell: "claude plugin install skill-heaven@gaia-skill-heaven", argv: ["claude", "plugin", "install", "skill-heaven@gaia-skill-heaven"], effect: "installs the skill-heaven plugin (runtime only)" }
      ],
      update: [
        { where: "shell", run: "claude plugin marketplace update gaia-skill-heaven", argv: ["claude", "plugin", "marketplace", "update", "gaia-skill-heaven"], effect: "refreshes the marketplace listing" },
        { where: "shell", run: "claude plugin uninstall skill-heaven@gaia-skill-heaven", argv: ["claude", "plugin", "uninstall", "skill-heaven@gaia-skill-heaven"], effect: "removes only the old cached runtime registration before reinstall" },
        { where: "shell", run: "claude plugin install skill-heaven@gaia-skill-heaven", argv: ["claude", "plugin", "install", "skill-heaven@gaia-skill-heaven"], effect: "installs the staged candidate even when the version string is unchanged" }
      ],
      remove: [{ where: "shell", run: "claude plugin uninstall skill-heaven@gaia-skill-heaven", argv: ["claude", "plugin", "uninstall", "skill-heaven@gaia-skill-heaven"], effect: "removes the plugin" }]
    },
    consolePiece: {
      register: [
        { where: "harness", run: "/plugin install skill-heaven-console@gaia-skill-heaven", shell: "claude plugin install skill-heaven-console@gaia-skill-heaven", argv: ["claude", "plugin", "install", "skill-heaven-console@gaia-skill-heaven"], effect: "installs the console plugin beside skill-heaven" }
      ],
      update: [
        { where: "shell", run: "claude plugin marketplace update gaia-skill-heaven", argv: ["claude", "plugin", "marketplace", "update", "gaia-skill-heaven"], effect: "refreshes the registered local marketplace" },
        { where: "shell", run: "claude plugin uninstall skill-heaven-console@gaia-skill-heaven", argv: ["claude", "plugin", "uninstall", "skill-heaven-console@gaia-skill-heaven"], effect: "removes only the old cached console before reinstall" },
        { where: "shell", run: "claude plugin install skill-heaven-console@gaia-skill-heaven", argv: ["claude", "plugin", "install", "skill-heaven-console@gaia-skill-heaven"], effect: "installs the staged console even when its version string is unchanged" }
      ],
      remove: [{ where: "shell", run: "claude plugin uninstall skill-heaven-console@gaia-skill-heaven", argv: ["claude", "plugin", "uninstall", "skill-heaven-console@gaia-skill-heaven"], effect: "removes only the console; skill-heaven is unchanged" }]
    },
    fullBlocked: null
  },
  {
    id: "codex",
    ...adapterPath("codex"),
    name: "Codex",
    bin: "codex",
    chip: "compatible",
    probedVersion: "0.161.0",
    evidence: "Live smoke on 0.161.0: plugin added, codex mcp list resolves skill-summon, a summon call completed. Headless codex exec asks approval for MCP calls. Surfaces last probed on 0.146.0.",
    evidenceHref: `${REPO}/plugins/skill-heaven/PROBE.md`,
    needsInstaller: true,
    commands: [
      `codex plugin marketplace add "${AGENT_PLUGIN_INSTALL.marketplace}"`,
      "codex plugin add skill-heaven@gaia-skill-heaven"
    ],
    inHarness: false,
    blocked: null,
    update: "Re-run the installer, then reinstall in Codex \u2014 Codex keeps its own cached copy.",
    remove: ["codex plugin remove skill-heaven@gaia-skill-heaven", AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "UNSUPPORTED",
    statusNote: "Codex has no public status contribution API. Summon receipts still print in the transcript.",
    launcher: "codex-zero",
    firstRun: "/summon <what you need>"
  },
  {
    id: "pi",
    ...adapterPath("pi"),
    name: "Pi",
    bin: "pi",
    chip: "compatible",
    probedVersion: "1.0.4",
    evidence: "Live probe on 1.0.4: pi install, five commands, summon materialized a skill, the four surfaces expanded. The adapter keeps its own summon tool rather than Pi's MCP runtime, which an MCP extension can replace.",
    evidenceHref: `${REPO}/plugins/skill-heaven/dev.skill-heaven.pi/PROBE.md`,
    needsInstaller: true,
    commands: [`pi install "${AGENT_PLUGIN_INSTALL.plugin}" --approve`],
    inHarness: false,
    blocked: null,
    update: "Re-run the installer, then pi update.",
    remove: [`pi remove "${AGENT_PLUGIN_INSTALL.plugin}"`, AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "NATIVE SLOT",
    statusNote: "Full adds a separate extension with its own setStatus key (API probed on 1.0.4); the new adapter's live TUI paint remains unprobed. Core has no console.",
    launcher: "pi-zero",
    firstRun: "/summon <what you need>"
  },
  {
    id: "grok",
    ...adapterPath("grok"),
    name: "Grok",
    bin: "grok",
    chip: "compatible",
    probedVersion: "1.0.5",
    evidence: "Live probe on 1.0.5. On 1.0.46, grok plugin install and details find the skills, commands and MCP server (static: no signed-in session to run a summon).",
    evidenceHref: `${REPO}/plugins/skill-heaven/PROBE.md`,
    needsInstaller: true,
    commands: [`grok plugin install "${AGENT_PLUGIN_INSTALL.plugin}" --trust`],
    inHarness: false,
    blocked: null,
    update: "Re-run the installer, then grok plugin update.",
    remove: ["grok plugin uninstall skill-heaven", AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "UNSUPPORTED",
    statusNote: "Full carries Status in an explicit command-backed report, not a persistent HUD.",
    launcher: "grok-zero",
    firstRun: "/summon <what you need>"
  },
  {
    id: "hermes",
    ...adapterPath("hermes"),
    name: "Hermes",
    bin: "hermes",
    chip: "compatible",
    probedVersion: "0.20.0",
    evidence: "Live probe, repeated on 0.20.0 (2026-10-08): plugin installed and enabled, a summon call completed.",
    evidenceHref: `${REPO}/plugins/skill-heaven/PROBE.md`,
    needsInstaller: true,
    commands: [`hermes plugins install "file://${AGENT_PLUGIN_INSTALL.plugin}" --enable`],
    inHarness: false,
    blocked: null,
    update: "Re-run the installer, then reinstall in Hermes. Remove the Hermes registration with Hermes's own plugin manager.",
    // Hermes's own removal command was not verified on the machine that wrote
    // this table (its `--help` could not run), so none is printed.
    remove: [AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "UNSUPPORTED",
    statusNote: "Hermes has no stable public status contribution. Receipts print in the transcript.",
    launcher: "hermes-zero",
    firstRun: "/summon <what you need>"
  },
  {
    id: "agy",
    ...adapterPath("agy"),
    name: "Antigravity",
    bin: "agy",
    chip: "compatible",
    probedVersion: "1.3.1",
    evidence: "Live probe on 1.3.1 with your real HOME: agy plugin install loads the skills, commands and the summon server; /skill-heaven:summon and the four surfaces ran.",
    evidenceHref: `${REPO}/packages/agy-zero/PROBE.md`,
    needsInstaller: true,
    commands: [`agy plugin install "${AGENT_PLUGIN_INSTALL.plugin}"`],
    inHarness: false,
    blocked: null,
    update: "Re-run the installer, then agy plugin uninstall skill-heaven and install it again \u2014 Antigravity keeps its own copy.",
    remove: ["agy plugin uninstall skill-heaven", AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "UNSUPPORTED",
    statusNote: "Full carries Status in an explicit skill report. No user statusLine is installed or rewritten.",
    launcher: "agy-zero",
    // Antigravity namespaces plugin skills: its / menu lists /skill-heaven:summon, and a bare /summon is not a command.
    firstRun: "/skill-heaven:summon <what you need>"
  },
  {
    id: "other",
    ...PENDING("Another"),
    name: "Another Agent Plugins client",
    bin: null,
    chip: "unverified",
    probedVersion: null,
    evidence: "The package follows Agent Plugins 1.0.0. Your client owns registration; it has not been probed here.",
    evidenceHref: "https://agent-plugins.org/specification",
    needsInstaller: true,
    commands: [],
    inHarness: false,
    blocked: `Point your client's own plugin install at ${AGENT_PLUGIN_INSTALL.plugin}. There is no universal registration command.`,
    update: "Re-run the installer; your client may keep its own cached copy.",
    remove: [AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "UNSUPPORTED",
    statusNote: "Depends on your client.",
    launcher: null,
    firstRun: "/summon <what you need>, or the spelling your client lists for the skill-heaven plugin"
  }
];
var CHIP_LABEL = {
  verified: "Verified",
  compatible: "Compatible",
  partial: "Partial",
  unverified: "Unverified",
  "needs-local-probe": "Needs local probe"
};
function harnessById(id) {
  const found = HARNESS_PATHS.find((h) => h.id === id);
  if (!found) throw new Error(`unknown harness ${id}`);
  return found;
}

// packages/status/src/console-host.ts
var CONSOLE_SURFACES = ["status", "lens", "session", "scope", "flow", "trust"];
var SURFACE_LABEL = Object.freeze({
  status: "Status",
  lens: "Lens",
  session: "Session",
  scope: "Scope",
  flow: "Flow",
  trust: "Trust"
});
var SURFACE_QUESTION = Object.freeze({
  status: "Where am I on the line, and how many skills entered this session?",
  lens: "What would a summon return \u2014 and hand it to me to submit.",
  session: "What happened, and what is the evidence for each step?",
  scope: "What can Skill Heaven see, what is active, which rung did I pick?",
  flow: "Which agents ran, and which skills did each summon?",
  trust: "What is installed, what can it read and write, what is degraded here?"
});

// packages/status/src/console-state.ts
var MAX_ENTRIES = 50;
var MAX_AGENTS = 100;
var MAX_SKILLS_PER_ENTRY = 20;
function initialConsoleState() {
  return {
    status: {
      ...emptyStatus(),
      reading: { kind: "native", source: "no-launcher" },
      skills: 0,
      summons: 0,
      summonTool: "unknown"
    },
    entries: [],
    band: null,
    agents: [],
    agentIdsSeen: false,
    selectedFrom: null,
    hostVersion: null,
    seq: 0
  };
}
var isRec2 = (v) => typeof v === "object" && v !== null && !Array.isArray(v);
var looksLikeSummon = (v) => isRec2(v) && ("summoned" in v || "previewed" in v || "noMatch" in v);
function structuredOf(r) {
  if (typeof r === "string") {
    const parsed = parseJson(r);
    if (looksLikeSummon(parsed)) return parsed;
    const embedded = firstJsonObject(r);
    return looksLikeSummon(embedded) ? embedded : void 0;
  }
  if (!isRec2(r)) return void 0;
  if (looksLikeSummon(r)) return r;
  const result = r.result;
  if (isRec2(result)) {
    if (looksLikeSummon(result.structuredContent)) return result.structuredContent;
    if (looksLikeSummon(result)) return result;
  }
  if (looksLikeSummon(r.structuredContent)) return r.structuredContent;
  const texts = [];
  if (typeof r.text === "string") texts.push(r.text);
  if (typeof result === "string" && result !== r.text) texts.push(result);
  for (const holder of [result, r]) {
    if (isRec2(holder) && Array.isArray(holder.content)) {
      for (const block of holder.content) {
        if (isRec2(block) && typeof block.text === "string") texts.push(block.text);
      }
    }
  }
  for (const text of texts) {
    const parsed = parseJson(text);
    if (looksLikeSummon(parsed)) return parsed;
    const embedded = firstJsonObject(text);
    if (looksLikeSummon(embedded)) return embedded;
  }
  return void 0;
}
function parseJson(text) {
  try {
    return JSON.parse(text);
  } catch {
    return void 0;
  }
}
function firstJsonObject(text) {
  for (let start = text.indexOf("{"); start !== -1; start = text.indexOf("{", start + 1)) {
    let depth = 0;
    let inString = false;
    for (let i = start; i < text.length; i++) {
      const ch = text[i];
      if (inString) {
        if (ch === "\\") i++;
        else if (ch === '"') inString = false;
      } else if (ch === '"') inString = true;
      else if (ch === "{") depth++;
      else if (ch === "}" && --depth === 0) {
        try {
          return JSON.parse(text.slice(start, i + 1));
        } catch {
          break;
        }
      }
    }
  }
  return void 0;
}
var shortId = (id) => sanitizeDisplay(id, 12);
function agentLabelFor(state, id) {
  if (id === null || id === void 0) return "main agent";
  const row = state.agents.find((a) => a.id === id);
  return row ? row.label : `agent ${shortId(id)}`;
}
function noteAgentId(state, id) {
  if (state.agents.some((a) => a.id === id)) return state.agentIdsSeen ? state : { ...state, agentIdsSeen: true };
  const agents = [
    ...state.agents,
    { key: id, id, label: `agent ${shortId(id)}`, state: "running" }
  ].slice(-MAX_AGENTS);
  return { ...state, agentIdsSeen: true, agents };
}
function bounded(event) {
  if ((event.kind === "summoned" || event.kind === "previewed") && event.skills.length > MAX_SKILLS_PER_ENTRY) {
    return { event: { ...event, skills: event.skills.slice(0, MAX_SKILLS_PER_ENTRY) }, omitted: event.skills.length - MAX_SKILLS_PER_ENTRY };
  }
  return { event, omitted: 0 };
}
function withReadObservability(event, readObservable) {
  if (readObservable || event.kind !== "summoned") return event;
  return {
    ...event,
    skills: event.skills.map((s) => s.stage === "materialized" ? { ...s, stage: "read-unobserved" } : s)
  };
}
function recordEvent(state, event, agent, via, opts = {}) {
  const reached = opts.reached ?? true;
  const shaped = withReadObservability(event, opts.readObservable ?? true);
  const id = state.seq + 1;
  const kept = bounded(shaped);
  const entry = {
    id,
    event: kept.event,
    omitted: kept.omitted,
    agent,
    via,
    readBy: "skills" in kept.event ? kept.event.skills.map(() => null) : []
  };
  const entries = [...state.entries, entry].slice(-MAX_ENTRIES);
  const withAgent = agent !== null ? noteAgentId(state, agent) : state;
  const status = reduceStatus(state.status, shaped);
  return {
    ...withAgent,
    status: reached ? { ...status, summonTool: "connected" } : status,
    entries,
    band: { kind: "event", id },
    seq: id
  };
}
function recordRead(state, path, reader) {
  let changed = false;
  const entries = state.entries.map((entry) => {
    const next = markRead(entry.event, path);
    if (next === entry.event) return entry;
    changed = true;
    const readBy = [...entry.readBy];
    if (next.kind === "summoned" && entry.event.kind === "summoned") {
      const before = entry.event.skills;
      next.skills.forEach((skill, i) => {
        if (skill.stage === "in-context" && before[i]?.stage !== "in-context") readBy[i] = reader;
      });
    }
    return { ...entry, event: next, readBy };
  });
  return changed ? { ...state, entries } : state;
}
function recordSelection(state, reading, typed) {
  return { ...state, status: withReading(state.status, reading), selectedFrom: sanitizeDisplay(typed, 40) };
}
function entryById(state, id) {
  return state.entries.find((e) => e.id === id);
}
function summonableName(skill) {
  if (!skill) return null;
  const name = sanitizeDisplay(skill.name, 64);
  return /^[A-Za-z0-9][A-Za-z0-9._:/-]*(?: [A-Za-z0-9._:/-]+)*$/.test(name) ? name : null;
}
var SURFACE_COMMANDS = /* @__PURE__ */ new Set(["summon", "skill-zero", "skill-heaven", "skill-hell", "skill-ultra"]);
function qualifyCommand(text, prefix = "skill-heaven:") {
  const m = /^\/([a-z-]+)(\s.*)?$/.exec(text);
  if (!m || !SURFACE_COMMANDS.has(m[1])) return text;
  return `/${prefix}${m[1]}${m[2] ?? ""}`;
}

// packages/status/src/console-view.ts
function evidenceWord(row) {
  const known = row.value !== null && row.value !== "" && row.evidence !== "unknown";
  if (row.evidence === "inferred") return "inferred";
  if (row.evidence === "unknown" || !known) return "unknown";
  return row.evidence;
}
function stageText(entry) {
  const event = entry.event;
  if (event.kind !== "summoned") return { text: "nothing materialized", inferred: false };
  const skills = event.skills;
  const inContext = skills.filter((s) => s.stage === "in-context");
  if (skills.length > 0 && inContext.length === skills.length) {
    const readers = Array.from(new Set(skills.map((_, i) => entry.readBy[i] ?? "an agent")));
    return { text: `in context \xB7 body read by ${readers.join(", ")}`, inferred: false };
  }
  if (inContext.length > 0) {
    return { text: `${inContext.length} of ${skills.length} in context \xB7 the rest: card returned \xB7 body not read`, inferred: false };
  }
  if (skills.length > 0 && skills.every((s) => s.stage === "read-unobserved")) {
    return { text: "materialized \xB7 read not observed on this host", inferred: false };
  }
  return { text: "card returned \xB7 body not read", inferred: true };
}
function summonSuggestion(entry) {
  const event = entry.event;
  if (event.kind !== "previewed" || event.skills.length !== 1) return null;
  return summonableName(event.skills[0]);
}
function lensView(state, projection2) {
  const band = state.band;
  if (band === null) return null;
  if (band.kind === "draft") {
    const args = JSON.stringify({ query: sanitizeDisplay(band.query, 4096), surface: "any", preview: true });
    return {
      lines: [[{ text: "Preview draft \xB7 not requested yet; no tool called", role: "dim" }]],
      stage: { text: "Submit the handoff yourself through the normal host tool/approval path. Nothing materialized.", inferred: false },
      actions: ["dismiss"],
      prefill: `Call the existing Skill Heaven summon tool with these JSON arguments: ${args}. Preview only; do not summon or read a skill body.`,
      entryId: null
    };
  }
  if (band.kind === "looking" || band.kind === "not-connected") {
    return {
      lines: noticeLines(band.kind === "looking" ? { kind: "looking", query: band.query } : { kind: "not-connected" }),
      stage: null,
      actions: ["dismiss"],
      prefill: null,
      entryId: null
    };
  }
  const entry = entryById(state, band.id);
  if (!entry) return null;
  const event = entry.event;
  const preview = event.kind === "previewed" || event.kind === "no-match" && event.preview;
  const name = summonSuggestion(entry);
  return {
    lines: eventLines(event),
    stage: preview ? null : stageText(entry),
    actions: name !== null ? ["summon", "inspect", "dismiss"] : ["inspect", "dismiss"],
    prefill: name !== null ? qualifyCommand(`/summon ${name}`, projection2.commandPrefix) : null,
    entryId: entry.id
  };
}
var DIRECTION_WORD = {
  manual: "any (explicit /summon)",
  converge: "heaven (converge)",
  explore: "hell (explore)",
  unspecified: "unspecified"
};
var LANE_WORD = {
  "human-led": "human-led (Skill Heaven lane)",
  "model-led": "model-led (Skill Hell lane)",
  unspecified: "unspecified (the source did not classify it)"
};
function healthText(event) {
  if (!("sourceHealth" in event)) return null;
  const h = event.sourceHealth;
  if (h.kind === "unknown") return null;
  const age = h.indexAgeDays === null ? "" : ` \xB7 index ${h.indexAgeDays} days old`;
  return h.kind === "stale" ? `? stale${age} \xB7 ranking still ran` : `fresh${age}`;
}
function skillRows(skill, index, entry) {
  const stage = skill.stage === "in-context" ? { label: "what entered", value: `body read (in context) by ${entry.readBy[index] ?? "an agent"}`, evidence: "observed" } : skill.stage === "materialized" ? { label: "what entered", value: "card returned \xB7 body not read", evidence: "inferred" } : skill.stage === "previewed" ? { label: "what entered", value: "previewed \xB7 nothing materialized", evidence: "reported" } : { label: "what entered", value: "materialized \xB7 read not observed", evidence: "unknown" };
  const rank = [];
  if (skill.matchKind !== "unknown") rank.push(skill.matchKind);
  const score = formatScore(skill.score);
  if (score) rank.push(score);
  const margin = formatScore(skill.margin);
  if (margin) rank.push(`\u0394 ${margin} (margin is a retrieval diagnostic)`);
  const from = [];
  if (skill.source) from.push(sanitizeDisplay(skill.source, 48));
  if (skill.repoUrl) from.push(sanitizeDisplay(skill.repoUrl, 64) + (skill.ref ? `@${sanitizeDisplay(skill.ref, 24)}` : ""));
  if (skill.subpath) from.push(sanitizeDisplay(skill.subpath, 48));
  if (skill.sha256) from.push(`sha256 ${sanitizeDisplay(skill.sha256, 12)}\u2026`);
  const cache = [];
  if (skill.cache !== "unknown") cache.push(skill.cache);
  const ms = formatMs(skill.ms);
  if (ms) cache.push(ms);
  const installability = skill.installability === "unknown" ? null : sanitizeDisplay(skill.installability, 40);
  const lane = LANE_WORD[skill.lane] ?? null;
  return [
    stage,
    { label: "ranking", value: rank.length ? rank.join(" \xB7 ") : null, evidence: rank.length ? "reported" : "unknown" },
    { label: "from", value: from.length ? from.join(" \xB7 ") : null, evidence: from.length ? "reported" : "unknown" },
    { label: "lane", value: lane, evidence: lane ? "reported" : "unknown" },
    { label: "installability", value: installability, evidence: installability ? "reported" : "unknown" },
    { label: "cache", value: cache.length ? cache.join(" \xB7 ") : null, evidence: cache.length ? "reported" : "unknown" },
    { label: "on disk", value: skill.path ? sanitizeDisplay(skill.path, 96) : null, evidence: skill.path ? "reported" : "unknown" }
  ];
}
function agentRow(state, entry) {
  return {
    label: "agent",
    value: agentLabelFor(state, entry.agent),
    evidence: entry.agent !== null ? "observed" : state.agentIdsSeen ? "observed" : "inferred"
  };
}
function receiptGroups(entry, state) {
  const event = entry.event;
  const query = "query" in event && event.query ? `query "${sanitizeDisplay(event.query, 80)}" \xB7 surface ${DIRECTION_WORD[event.direction] ?? "unspecified"}` : null;
  const health = healthText(event);
  const agent = agentRow(state, entry);
  if (event.kind === "summoned" || event.kind === "previewed") {
    const common = [{ label: "why", value: query, evidence: query ? "reported" : "unknown" }];
    if (event.kind === "summoned") {
      const comp = event.composition === "relevance-only" ? `relevance-only \xB7 Arbor: ${event.arbor === "governed-record" ? "governed record" : event.arbor === "no-record" ? "no governed record" : event.arbor}` : null;
      common.push({ label: "composition", value: comp, evidence: comp ? "reported" : "unknown" });
    }
    common.push({ label: "source health", value: health, evidence: health ? "reported" : "unknown" }, agent);
    const groups = [common];
    event.skills.slice(0, 3).forEach(
      (skill, i) => groups.push([{ label: "skill", value: sanitizeDisplay(skill.name, 48), evidence: "reported" }, ...skillRows(skill, i, entry)])
    );
    const unshown = event.skills.length - 3 + entry.omitted;
    if (unshown > 0) groups.push([{ label: "more", value: `+${unshown} more not shown here`, evidence: "observed" }]);
    return groups;
  }
  if (event.kind === "no-match") {
    return [
      [
        { label: "what entered", value: "nothing materialized", evidence: "reported" },
        { label: "why", value: query, evidence: query ? "reported" : "unknown" },
        {
          label: "refusal",
          value: (event.considered === null ? "0 admitted" : `${event.considered} considered \xB7 0 admitted`) + (event.reason ? ` \xB7 ${sanitizeDisplay(event.reason, 60)}` : ""),
          evidence: "reported"
        },
        { label: "source health", value: health, evidence: health ? "reported" : "unknown" },
        agent
      ]
    ];
  }
  return [
    [
      { label: "what entered", value: "nothing materialized", evidence: "reported" },
      { label: "reason", value: sanitizeDisplay(event.reason, 120), evidence: "observed" },
      agent
    ]
  ];
}
function timeLabel(at) {
  if (!at) return "";
  const d = new Date(at);
  if (Number.isNaN(d.getTime())) return "";
  const two = (n) => String(n).padStart(2, "0");
  return `${two(d.getHours())}:${two(d.getMinutes())}:${two(d.getSeconds())}`;
}
var EVIDENCE_LEGEND = "Evidence: observed = this console saw it \xB7 reported = the summon engine said so \xB7 inferred = derived here \xB7 unknown = no source.";
function sessionView(state, projection2) {
  const entries = [...state.entries].reverse().map((entry) => {
    const meta = [
      timeLabel(entry.event.at),
      agentLabelFor(state, entry.agent),
      entry.via === "lens" ? "/lens" : entry.via === "ledger" ? "engine ledger" : ""
    ].filter(Boolean).join(" \xB7 ");
    return { id: entry.id, lines: eventLines(entry.event), meta, groups: receiptGroups(entry, state), stage: stageText(entry) };
  });
  return {
    notConnected: state.status.summonTool === "not-connected",
    empty: entries.length === 0 ? `Nothing summoned yet. Try ${qualifyCommand("/summon", projection2.commandPrefix)} <need>${projection2.surfaces.lens.level === "unsupported" ? "" : ` or ${lensCommand(projection2)} <need>`}.` : null,
    entries,
    legend: EVIDENCE_LEGEND
  };
}
function lensCommand(projection2) {
  return projection2.kind === "command-backed" ? `${projection2.command ?? "/heaven"} lens` : "/lens";
}
var ULTRA_COPY = "Skill Ultra \xB7 provisioned. Controller unavailable \u2014 no controller is choosing direction or depth yet. Ultra is the rung you selected; each summon is still judged per use. The long-horizon controller is tracked in #126 and is not yet empirically validated.";
function latestSource(state) {
  const last = state.entries[state.entries.length - 1];
  const unavailable = last?.event.kind === "unavailable";
  for (let i = state.entries.length - 1; i >= 0; i--) {
    const e = state.entries[i];
    const event = e.event;
    if ("skills" in event) {
      const withSource = event.skills.find((s) => s.source);
      if (withSource?.source) return { source: sanitizeDisplay(withSource.source, 56), health: healthText(event), unavailable };
    }
  }
  return { source: null, health: last ? healthText(last.event) : null, unavailable };
}
function scopeView(state, harness) {
  const projection2 = harness.console;
  const sp = (c) => qualifyCommand(c, projection2.commandPrefix);
  const { source, health, unavailable } = latestSource(state);
  const reading = state.status.reading;
  const boot = state.status.boot ?? (reading.kind === "selected" ? { kind: "native", source: "no-launcher" } : reading);
  const rung = reading.kind === "selected" ? reading.rung : null;
  const ultra = readingRung(reading) === "ultra";
  const skills = state.status.skills;
  const rungObservable = projection2.observes.rung !== "unavailable";
  const rows = [
    {
      label: "can see",
      value: unavailable ? `skill source ${source ?? ""} \xB7 unreachable`.replace("  ", " ") : source ? `skill source ${source}${health ? ` \xB7 ${health}` : ""}` : null,
      evidence: source || unavailable ? "reported" : "unknown"
    },
    {
      label: "active",
      value: skills === null ? null : `${skills} ${skills === 1 ? "skill" : "skills"} materialized this session (temporary \u2014 gone when the session ends)`,
      evidence: skills === null ? "unknown" : projection2.observes.summon === "observed" ? "observed" : "reported"
    },
    {
      label: "inherited",
      value: boot.kind === "native" || boot.kind === "unknown" ? `boot reading ${readingToken(boot)} \u2014 no launcher observed; this console cannot see how the session was started` : `boot reading ${readingToken(boot)} \u2014 set at launch`,
      evidence: boot.kind === "native" || boot.kind === "unknown" ? "inferred" : "reported"
    },
    {
      label: "selected",
      value: rung === null ? rungObservable ? "none \u2014 no rung selected in this session" : "unknown \u2014 this host does not let the console see which rung command you typed" : ultra ? "rung ULTRA \xB7 controller unavailable" : `rung ${rung.toUpperCase()} \u2014 observed from ${state.selectedFrom ?? "a rung command"} \xB7 not enforced`,
      evidence: rung === null ? "unknown" : "observed"
    },
    { label: "allowed", value: "/summon by hand: yes \xB7 zero cut: temporary (default)", evidence: "reported" },
    {
      label: "keep small",
      value: `${sp("/skill-zero")} cuts temporary skills${harness.launcher ? ` \xB7 ${harness.launcher} --level zero starts clean` : ""}`,
      evidence: "reported"
    }
  ];
  return {
    rows,
    note: rung !== null && !ultra ? `You selected ${rung.toUpperCase()}. Skill Heaven does not enforce a rung; each summon is still judged per use.` : null,
    ultra: ultra ? ULTRA_COPY : null,
    rungControls: [
      { label: sp("/skill-heaven low"), kind: "prefill", text: "/skill-heaven low" },
      { label: sp("/skill-hell high"), kind: "prefill", text: "/skill-hell high" },
      { label: sp("/skill-ultra"), kind: "prefill", text: "/skill-ultra" }
    ],
    otherRungs: `Other rungs: ${sp("/skill-heaven med")} \xB7 ${sp("/skill-hell xhigh")} \xB7 ${sp("/skill-hell max")}`,
    keepSmall: [
      { label: sp("/skill-zero"), kind: "prefill", text: "/skill-zero" },
      { label: sp("/skill-zero all"), kind: "prefill", text: "/skill-zero all" },
      ...harness.launcher ? [{ label: `Copy: ${harness.launcher} --level zero`, kind: "copy", text: `${harness.launcher} --level zero` }] : []
    ],
    keepSmallNote: harness.launcher ? "Start clean is run in a terminal before a session: it is copied, not run." : null
  };
}
var FLOW_VISIBLE_LIMIT = 12;
function agentLine(state, agent) {
  const mine = state.entries.filter((e) => e.agent !== null && e.agent === agent.id && e.event.kind === "summoned");
  const skills = mine.reduce((n, e) => n + (e.event.kind === "summoned" ? e.event.delta : 0), 0);
  const word = agent.state === "started" ? "started in background" : agent.state;
  return `${word} \xB7 ${mine.length === 0 ? "no skills" : `${mine.length} ${mine.length === 1 ? "summon" : "summons"}`}${skills > 0 && skills !== mine.length ? ` (${skills} skills)` : ""}`;
}
function flowView(state, projection2) {
  const mainSummons = state.entries.filter((e) => e.agent === null && e.event.kind === "summoned");
  const mainInContext = mainSummons.reduce(
    (n, e) => n + (e.event.kind === "summoned" ? e.event.skills.filter((s) => s.stage === "in-context").length : 0),
    0
  );
  const shown = state.agents.slice(0, FLOW_VISIBLE_LIMIT);
  const more = Math.max(0, state.agents.length - shown.length);
  const readsKnown = projection2.observes.read !== "unavailable";
  const mainLine = `${mainSummons.length} ${mainSummons.length === 1 ? "summon" : "summons"} \xB7 ${readsKnown ? `${mainInContext} in context` : "reads not observed"}`;
  const noAgents = projection2.observes.agents === "unavailable";
  return {
    main: { summons: mainSummons.length, inContext: mainInContext, line: mainLine },
    agents: shown.map((agent, i) => ({
      label: sanitizeDisplay(agent.label, 64),
      line: agentLine(state, agent),
      last: i === shown.length - 1 && more <= 0
    })),
    more,
    telemetryNote: noAgents ? "This host does not report agent ids to the console. Summons are attributed to main." : !state.agentIdsSeen ? "This host did not report agent ids. Summons are attributed to main." : null,
    windowNote: state.entries.length >= 50 ? "Counts cover the last 50 events." : null,
    footer: "Read-only. Only agents the host reported appear."
  };
}
function trustView(state, harness) {
  const projection2 = harness.console;
  const mcp = state.status.summonTool;
  const mcpText = mcp === "connected" ? "connected (a summon result was seen)" : mcp === "not-connected" ? "not connected" : "unknown until the first summon or /lens";
  return {
    components: projection2.trust.map((c) => ({
      id: c.id,
      profile: c.profile,
      kind: c.kind,
      version: c.version,
      summary: c.summary,
      notes: c.notes ?? [],
      rows: [
        { label: "reads", value: c.reads.join(" \xB7 "), evidence: "reported" },
        { label: "writes", value: c.writes.length ? c.writes.join(" \xB7 ") : "nothing", evidence: "reported" },
        { label: "network", value: c.network, evidence: "reported" },
        { label: "disable", value: c.disable, evidence: "reported" }
      ]
    })),
    rows: [
      { label: "summon tool", value: `MCP: ${mcpText}`, evidence: "reported" },
      {
        label: "harness",
        value: `${harness.name} ${state.hostVersion ? sanitizeDisplay(state.hostVersion, 24) : "(version not reported)"} \xB7 ${CHIP_LABEL[harness.chip]} for the plugin at ${harness.probedVersion ?? "unknown"}`,
        evidence: state.hostVersion ? "observed" : "unknown"
      },
      { label: "evidence", value: harness.evidence, evidence: "reported" },
      { label: "console probe", value: projection2.probe.summary, evidence: "reported" }
    ],
    hostLimits: CONSOLE_SURFACES.filter((s) => projection2.surfaces[s].level !== "native").map((surface) => ({
      surface,
      level: projection2.surfaces[surface].level,
      via: projection2.surfaces[surface].via,
      note: projection2.surfaces[surface].note
    })),
    footer: "This lists what the code can do. It does not rate it."
  };
}
function buildConsoleView(state, harness) {
  const projection2 = harness.console;
  const segments = renderStatusSegments(state.status, "full");
  return {
    harness: { id: harness.id, name: harness.name, chip: harness.chip, probedVersion: harness.probedVersion },
    projection: projection2,
    status: { segments, plain: toPlain(segments), compact: toPlain(renderStatusSegments(state.status, "compact")) },
    lens: lensView(state, projection2),
    session: sessionView(state, projection2),
    scope: scopeView(state, harness),
    flow: flowView(state, projection2),
    trust: trustView(state, harness)
  };
}
var SUPPORT_WORD = {
  native: "native",
  degraded: "degraded (native fallback)",
  unsupported: "unsupported on this host"
};
function paint(segments, color) {
  return color === "none" ? toPlain(segments) : paintAnsi(segments, color);
}
function rowLine(row, labelWidth = 16) {
  const known = row.value !== null && row.value !== "" && row.evidence !== "unknown";
  return `${row.label.padEnd(labelWidth)}${known ? row.value : "\u2014"}  ${evidenceWord(row)}`;
}
function wrap(text, width, indent) {
  if (width <= 0 || text.length <= width) return `${indent}${text}`;
  const words = text.split(" ");
  const lines = [];
  let line = "";
  for (const w of words) {
    if (line && (indent + line + " " + w).length > width) {
      lines.push(indent + line);
      line = w;
    } else {
      line = line ? `${line} ${w}` : w;
    }
  }
  if (line) lines.push(indent + line);
  return lines.join("\n");
}
function header(view, surface) {
  const support = view.projection.surfaces[surface];
  return [`\u2500\u2500 ${SURFACE_LABEL[surface]} \xB7 ${SUPPORT_WORD[support.level]} \u2500\u2500`, ...support.level === "native" ? [] : [`   via ${support.via}. ${support.note}`]];
}
function renderConsoleText(view, opts = {}) {
  const color = opts.color ?? "none";
  const width = opts.width ?? 0;
  const which = opts.surface ?? "all";
  const want = (s) => which === "all" || which === s;
  const out = [];
  out.push(`Skill Heaven console \xB7 ${view.harness.name} \xB7 ${view.projection.kind === "command-backed" ? "command-backed" : view.projection.kind === "pane" ? "pane" : "extension UI"} \xB7 observes, never changes`);
  out.push(paint(view.status.segments, color));
  if (want("status")) {
    out.push("", ...header(view, "status"), `   ${view.status.compact}`);
  }
  if (want("lens")) {
    out.push("", ...header(view, "lens"));
    if (view.lens === null) {
      out.push("   (empty \u2014 Lens shows a result only after a summon or a preview)");
    } else {
      for (const l of view.lens.lines) out.push(`   ${paint(l, color)}`);
      if (view.lens.stage) out.push(`   ${view.lens.stage.text}${view.lens.stage.inferred ? " (inferred)" : ""}`);
      if (view.lens.prefill) out.push(`   To summon, type: ${view.lens.prefill}   (nothing is submitted for you)`);
    }
  }
  if (want("session")) {
    out.push("", ...header(view, "session"));
    if (view.session.notConnected) out.push("   ? summon tool: not connected");
    if (view.session.empty) out.push(`   ${view.session.empty}`);
    for (const e of view.session.entries) {
      const [l1, l2] = e.lines;
      if (l1) out.push(`   ${paint(l1, color)}${e.meta ? `   ${e.meta}` : ""}`);
      if (l2) out.push(`   ${paint(l2, color)}`);
      for (const g of e.groups) {
        for (const r of g) out.push(wrap(rowLine(r), width, "      "));
        out.push("");
      }
    }
    out.push(`   ${view.session.legend}`);
  }
  if (want("scope")) {
    out.push("", ...header(view, "scope"));
    for (const r of view.scope.rows) out.push(wrap(rowLine(r), width, "   "));
    if (view.scope.note) out.push(`   ${view.scope.note}`);
    if (view.scope.ultra) out.push(wrap(view.scope.ultra, width, "   "));
    out.push("   Choose a rung \u2014 type one; nothing runs until you submit it:");
    for (const c of view.scope.rungControls) out.push(`     ${c.label}`);
    out.push(`   ${view.scope.otherRungs}`);
    out.push("   Keep context small:");
    for (const c of view.scope.keepSmall) out.push(`     ${c.label}`);
    if (view.scope.keepSmallNote) out.push(`   ${view.scope.keepSmallNote}`);
  }
  if (want("flow")) {
    out.push("", ...header(view, "flow"));
    out.push(`   main   ${view.flow.main.line}`);
    for (const a of view.flow.agents) out.push(`   ${a.last ? "\u2514\u2500" : "\u251C\u2500"} ${a.label}   ${a.line}`);
    if (view.flow.more > 0) out.push(`   \u2514\u2500 +${view.flow.more} more`);
    if (view.flow.telemetryNote) out.push(`   ${view.flow.telemetryNote}`);
    if (view.flow.windowNote) out.push(`   ${view.flow.windowNote}`);
    out.push(`   ${view.flow.footer}`);
  }
  if (want("trust")) {
    out.push("", ...header(view, "trust"));
    for (const c of view.trust.components) {
      out.push(`   ${c.id} ${c.version} (${c.profile}) \xB7 ${c.kind} \xB7 ${c.summary}`);
      for (const r of c.rows) out.push(wrap(rowLine(r), width, "     "));
      for (const n of c.notes) out.push(wrap(n, width, "     "));
    }
    for (const r of view.trust.rows) out.push(wrap(rowLine(r), width, "   "));
    if (view.trust.hostLimits.length > 0) {
      out.push("   On this host:");
      for (const l of view.trust.hostLimits) out.push(wrap(`${SURFACE_LABEL[l.surface]} \u2014 ${SUPPORT_WORD[l.level]}: ${l.note}`, width, "     "));
    }
    out.push(`   ${view.trust.footer}`);
  }
  return out.join("\n");
}

// packages/status/src/install-plan.ts
var DEFAULT_PLAN_PATHS = {
  pluginDir: AGENT_PLUGIN_INSTALL.plugin,
  marketplaceDir: AGENT_PLUGIN_INSTALL.marketplace,
  consoleDir: `${AGENT_PLUGIN_INSTALL.root}/marketplace/plugins/skill-heaven-console`
};

// packages/console/extension/console.ts
var KEY = "skill-heaven-console";
var projection = harnessById("pi");
function consolePi(pi) {
  let state = initialConsoleState();
  const paint2 = (ctx) => {
    if (!ctx.hasUI) return;
    ctx.ui.setStatus(KEY, process.env.SKILL_HEAVEN_STATUS === "off" ? void 0 : buildConsoleView(state, projection).status.compact);
  };
  const rebuild = (ctx) => {
    state = initialConsoleState();
    const branch = ctx.sessionManager.getBranch();
    for (const entry of branch.slice(-1e3)) {
      if (entry.type !== "message" || entry.message.role !== "toolResult") continue;
      const message = entry.message;
      if (message.toolName === "summon") {
        const structured = structuredOf(message.details);
        if (structured) state = recordEvent(state, eventFromSummonResult(structured), null, "tool", { readObservable: false });
      }
    }
    if (branch.length > 1e3) state.status = { ...state.status, skills: null, summons: null };
    paint2(ctx);
    if (ctx.hasUI) ctx.ui.setWidget(KEY, void 0);
  };
  pi.on("session_start", (_e, ctx) => rebuild(ctx));
  pi.on("session_tree", (_e, ctx) => rebuild(ctx));
  pi.on("tool_result", (event, ctx) => {
    if (event.toolName === "summon") {
      const structured = structuredOf(event.details) ?? structuredOf({ content: event.content });
      state = recordEvent(state, eventFromSummonResult(structured, { preview: event.input.preview === true }, event.isError ? { isError: true, text: "Core summon failed" } : void 0), null, "tool");
    } else if (event.toolName === "read" && !event.isError && typeof event.input.path === "string") {
      state = recordRead(state, resolve(ctx.cwd, event.input.path), "main agent");
    }
    paint2(ctx);
  });
  pi.on("input", (event, ctx) => {
    const typed = event.text.replace(/^\/skill:/, "/");
    const reading = selectionFromCommand(typed);
    if (reading) {
      state = recordSelection(state, reading, typed);
      paint2(ctx);
    }
  });
  const show = (ctx, surface = "all") => {
    if (ctx.hasUI) ctx.ui.setWidget(KEY, renderConsoleText(buildConsoleView(state, projection), { surface }).split("\n"), { placement: "belowEditor" });
  };
  pi.registerCommand("heaven", {
    description: "Skill Heaven console; [status|lens|session|scope|flow|trust|dismiss|fill]",
    handler: async (args, ctx) => {
      if (!ctx.hasUI) return;
      const sub = args.trim() || "all";
      if (sub === "dismiss") {
        state = { ...state, band: null };
        ctx.ui.setWidget(KEY, void 0);
        return;
      }
      if (sub === "fill") {
        const draft = buildConsoleView(state, projection).lens?.prefill;
        if (draft) ctx.ui.setEditorText(draft);
        return;
      }
      if (sub === "all" || CONSOLE_SURFACES.includes(sub)) show(ctx, sub);
      else ctx.ui.notify("Usage: /heaven [status|lens|session|scope|flow|trust|dismiss|fill]", "info");
    }
  });
  pi.registerCommand("lens", {
    description: "Draft a preview handoff; /heaven fill prefills, you submit it",
    handler: async (args, ctx) => {
      const query = args.trim();
      if (!query || query.length > 4096 || !ctx.hasUI) return;
      state = { ...state, band: { kind: "draft", query } };
      show(ctx, "lens");
    }
  });
  pi.on("session_shutdown", (_e, ctx) => {
    if (ctx.hasUI) {
      ctx.ui.setStatus(KEY, void 0);
      ctx.ui.setWidget(KEY, void 0);
    }
  });
}
export {
  consolePi as default
};
