#!/usr/bin/env node
// Separate, removable console artifacts. No root build scripts or existing status builder modified.
import { build } from "esbuild";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");
for (const host of ["pi", "codex", "hermes", "grok", "agy"]) {
  const file = resolve(root, `plugins/skill-heaven-console-${host}/${host === "pi" ? "extensions/console.mjs" : "scripts/heaven.mjs"}`);
  const result = await build({ entryPoints: [resolve(root, `packages/console/${host === "pi" ? "extension/console" : "src/cli"}.ts`)], bundle: true, format: "esm", platform: "node", target: "node22", write: false, legalComments: "none", logLevel: "silent", external: ["@earendil-works/pi-coding-agent", "@earendil-works/pi-tui"] });
  const code = "// @ts-nocheck — generated from type-checked source.\n// GENERATED by scripts/build-console.mjs — do not edit.\n" + result.outputFiles[0].text;
  if (/STATUS_FIXTURES|EVENT_FIXTURES/.test(code)) throw new Error("runtime console must not bundle fixtures");
  let previous = "";
  try { previous = readFileSync(file, "utf8"); } catch {}
  if (code !== previous) {
    if (check) throw new Error(`stale console bundle: ${file}`);
    mkdirSync(dirname(file), { recursive: true }); writeFileSync(file, code);
  }
  console.log(`console ${host}: ${code.length} bytes${check ? " (checked)" : ""}`);
}
