#!/usr/bin/env node
// Bundles the one status model (packages/status) into the Claude Code console
// mod. A mod runs in an environment with no Node and imports only files inside
// its own plugin folder, so it cannot reach packages/status at run time; it
// gets this committed, CI-checked copy instead — one model, not two.
//
// Source:  packages/status/src/index.ts   (fixtures are not exported, so not bundled)
// Output:  plugins/skill-heaven-console/hooks/status-model.mjs  (COMMITTED to git)
//
// Rebuild with: npm run build:status
// CI fails the build if the committed output drifts from a fresh rebuild.

import { build } from "esbuild";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");
const entry = join(repoRoot, "packages/status/src/index.ts");
const outfile = join(repoRoot, "plugins/skill-heaven-console/hooks/status-model.mjs");

const result = await build({
  entryPoints: [entry],
  bundle: true,
  format: "esm",
  platform: "neutral",
  target: "es2022",
  write: false,
  legalComments: "none",
  logLevel: "silent",
});

const code = result.outputFiles[0].text;
if (/from\s+["']node:|require\(/.test(code)) {
  throw new Error("status bundle must stay Node-free: the console mod runs without Node");
}
if (/STATUS_FIXTURES|EVENT_FIXTURES/.test(code)) {
  throw new Error("status bundle must not carry fixtures: runtime projections cannot reach design data");
}

const header =
  "// GENERATED by scripts/build-status.mjs from packages/status/src — do not edit.\n" +
  "// One status model for every projection (docs/CONTROL-PLANE.md).\n";
mkdirSync(dirname(outfile), { recursive: true });
const next = header + code;
let previous = "";
try {
  previous = readFileSync(outfile, "utf8");
} catch {}
if (previous !== next) writeFileSync(outfile, next);
console.log(`status bundle: ${outfile} (${next.length} bytes${previous === next ? ", unchanged" : ""})`);
