// @ts-nocheck
// Generated by npm run build:profiles — typed source: scripts/install-profile.ts; do not edit.

// scripts/install-profile.ts
import { spawnSync } from "node:child_process";
import { cpSync, existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// packages/status/src/compat.ts
var AGENT_PLUGIN_INSTALL = {
  posix: "curl -fsSL https://gaia-research.github.io/gaia-skill-heaven/install-agent-plugin.sh | sh",
  windows: "irm https://gaia-research.github.io/gaia-skill-heaven/install-agent-plugin.ps1 | iex",
  root: "$HOME/.local/share/gaia-skill-heaven-agent-plugin",
  marketplace: "$HOME/.local/share/gaia-skill-heaven-agent-plugin/marketplace",
  plugin: "$HOME/.local/share/gaia-skill-heaven-agent-plugin/marketplace/plugins/skill-heaven",
  uninstall: "$HOME/.local/share/gaia-skill-heaven-agent-plugin/uninstall.sh"
};
var PROFILE_PITCH = {
  core: { name: "Core", line: "The Skill Heaven runtime. Summon and the entropy controls. No extra console UI." },
  full: {
    name: "Full",
    line: "Core, plus the native Skill Heaven console for your harness \u2014 status, Lens, Session, Scope, Flow and Trust where the harness supports them."
  }
};
var PENDING = (name) => ({
  console: {
    kind: "command-backed",
    mechanism: `pending recon for ${name}`,
    command: null,
    commandPrefix: "",
    surfaces: {
      status: { level: "unsupported", via: "pending", note: "pending" },
      lens: { level: "unsupported", via: "pending", note: "pending" },
      session: { level: "unsupported", via: "pending", note: "pending" },
      scope: { level: "unsupported", via: "pending", note: "pending" },
      flow: { level: "unsupported", via: "pending", note: "pending" },
      trust: { level: "unsupported", via: "pending", note: "pending" }
    },
    observes: { summon: "unavailable", read: "unavailable", agents: "unavailable", rung: "unavailable" },
    summonTools: [],
    trust: [],
    probe: { version: null, summary: "pending", href: null }
  },
  core: { register: [], update: [], remove: [] },
  consolePiece: null,
  fullBlocked: "pending recon"
});
var REPO = "https://github.com/gaia-research/gaia-skill-heaven/blob/main";
var HARNESS_PATHS = [
  {
    id: "claude",
    name: "Claude Code",
    bin: "claude",
    chip: "verified",
    probedVersion: "2.1.288",
    evidence: "Fresh-install receipt, 76/76 checks, GitHub main @ fdfd94e.",
    evidenceHref: `${REPO}/docs/RELEASE-ACCEPTANCE.md`,
    needsInstaller: false,
    commands: [
      "/plugin marketplace add gaia-research/gaia-skill-heaven",
      "/plugin install skill-heaven@gaia-skill-heaven"
    ],
    inHarness: true,
    blocked: null,
    update: "claude plugin marketplace update gaia-skill-heaven && claude plugin update skill-heaven@gaia-skill-heaven",
    remove: ["claude plugin uninstall skill-heaven@gaia-skill-heaven"],
    statusIntegration: "APPEND",
    statusNote: "The optional console (preview) adds a status entry beside yours \u2014 it never replaces your statusLine. Probed live in the terminal on 2.1.294; its desktop paint is not probed.",
    launcher: "claude-zero",
    // 2.1.294 refuses a bare /summon: it resolves to the portable skill, which is user-invocable: false.
    firstRun: "/skill-heaven:summon <what you need>",
    console: {
      kind: "pane",
      mechanism: "Claude Code's Mods API (function hooks, early access since 2.1.293): $.ui.status appends a status entry beside your own, an AbovePrompt band carries Lens, and /heaven opens a pane with Session, Scope, Flow and Trust.",
      command: "/heaven",
      commandPrefix: "skill-heaven:",
      surfaces: {
        status: { level: "native", via: "$.ui.status (APPEND \u2014 never touches statusLine)", note: "Probed live in the terminal on 2.1.294; desktop paint is not probed." },
        lens: { level: "native", via: "AbovePrompt band + $.prompt.fill", note: "A button only pre-fills the prompt; you press Enter." },
        session: { level: "native", via: "the /heaven pane", note: "Every field carries an evidence class." },
        scope: { level: "native", via: "the /heaven pane", note: "Rung controls pre-fill commands; nothing runs until you submit." },
        flow: { level: "native", via: "agentId on tool.call and turn.complete", note: "Only agents the host reported appear." },
        trust: { level: "native", via: "the /heaven pane", note: "Lists what the console reads and writes; it does not rate it." }
      },
      observes: { summon: "observed", read: "observed", agents: "observed", rung: "observed" },
      summonTools: ["mcp__plugin_skill-heaven_skill-summon__summon", "mcp__skill-summon__summon"],
      trust: [
        {
          id: "skill-heaven",
          profile: "core",
          kind: "Claude Code plugin",
          version: "0.1.2",
          summary: "The runtime: five commands and one bundled MCP server (skill-summon).",
          reads: ["the skill source you configure (network, by the summon tool)"],
          writes: ["a disposable session directory under your temp dir"],
          network: "the summon tool fetches the skill source",
          disable: "claude plugin uninstall skill-heaven@gaia-skill-heaven"
        },
        {
          id: "skill-heaven-console",
          profile: "full",
          kind: "Claude Code plugin (Mods, preview)",
          version: "0.1.0",
          summary: "The console: a status entry, the Lens band and the /heaven pane. Runs inside Claude Code as local code.",
          notes: ["/lens and /heaven print a one-line result that the model can read. It is fixed text and carries nothing a skill source supplied."],
          reads: ["summon tool results", "your /skill-* commands", "Read and Agent tool calls \u2014 to observe, never to change"],
          writes: ["nothing to disk", "session-only $.state"],
          network: "none of its own; /lens calls the bundled summon tool, which fetches the skill source",
          disable: "claude plugin uninstall skill-heaven-console@gaia-skill-heaven"
        }
      ],
      probe: {
        version: "2.1.294",
        summary: "the console was probed live in the terminal on 2.1.294; desktop paint is not probed",
        href: `${REPO}/plugins/skill-heaven-console/README.md`
      }
    },
    core: {
      register: [
        { where: "harness", run: "/plugin marketplace add gaia-research/gaia-skill-heaven", shell: "claude plugin marketplace add gaia-research/gaia-skill-heaven", effect: "adds the gaia-skill-heaven marketplace to Claude Code's plugin registry" },
        { where: "harness", run: "/plugin install skill-heaven@gaia-skill-heaven", shell: "claude plugin install skill-heaven@gaia-skill-heaven", effect: "installs the skill-heaven plugin (runtime only)" }
      ],
      update: [
        { where: "shell", run: "claude plugin marketplace update gaia-skill-heaven", effect: "refreshes the marketplace listing" },
        { where: "shell", run: "claude plugin update skill-heaven@gaia-skill-heaven", effect: "updates the plugin to the listed version" }
      ],
      remove: [{ where: "shell", run: "claude plugin uninstall skill-heaven@gaia-skill-heaven", effect: "removes the plugin" }]
    },
    consolePiece: {
      register: [
        { where: "harness", run: "/plugin install skill-heaven-console@gaia-skill-heaven", shell: "claude plugin install skill-heaven-console@gaia-skill-heaven", effect: "installs the console plugin beside skill-heaven" }
      ],
      update: [{ where: "shell", run: "claude plugin update skill-heaven-console@gaia-skill-heaven", effect: "updates the console plugin" }],
      remove: [{ where: "shell", run: "claude plugin uninstall skill-heaven-console@gaia-skill-heaven", effect: "removes only the console; skill-heaven is unchanged" }]
    },
    fullBlocked: null
  },
  {
    id: "codex",
    ...PENDING("Codex"),
    name: "Codex",
    bin: "codex",
    chip: "compatible",
    probedVersion: "0.161.0",
    evidence: "Live smoke on 0.161.0: plugin added, codex mcp list resolves skill-summon, a summon call completed. Headless codex exec asks approval for MCP calls. Surfaces last probed on 0.146.0.",
    evidenceHref: `${REPO}/plugins/skill-heaven/PROBE.md`,
    needsInstaller: true,
    commands: [
      `codex plugin marketplace add "${AGENT_PLUGIN_INSTALL.marketplace}"`,
      "codex plugin add skill-heaven@gaia-skill-heaven"
    ],
    inHarness: false,
    blocked: null,
    update: "Re-run the installer, then reinstall in Codex \u2014 Codex keeps its own cached copy.",
    remove: ["codex plugin remove skill-heaven@gaia-skill-heaven", AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "UNSUPPORTED",
    statusNote: "Codex has no public status contribution API. Summon receipts still print in the transcript.",
    launcher: "codex-zero",
    firstRun: "/summon <what you need>"
  },
  {
    id: "pi",
    ...PENDING("Pi"),
    name: "Pi",
    bin: "pi",
    chip: "compatible",
    probedVersion: "1.0.4",
    evidence: "Live probe on 1.0.4: pi install, five commands, summon materialized a skill, the four surfaces expanded. The adapter keeps its own summon tool rather than Pi's MCP runtime, which an MCP extension can replace.",
    evidenceHref: `${REPO}/plugins/skill-heaven/dev.skill-heaven.pi/PROBE.md`,
    needsInstaller: true,
    commands: [`pi install "${AGENT_PLUGIN_INSTALL.plugin}" --approve`],
    inHarness: false,
    blocked: null,
    update: "Re-run the installer, then pi update.",
    remove: [`pi remove "${AGENT_PLUGIN_INSTALL.plugin}"`, AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "NATIVE SLOT",
    statusNote: "Pi's status API takes the canonical entropy line (probed on 1.0.4, appended under its own key); the plugin does not draw it yet. The pi-zero extension draws a widget.",
    launcher: "pi-zero",
    firstRun: "/summon <what you need>"
  },
  {
    id: "grok",
    ...PENDING("Grok"),
    name: "Grok",
    bin: "grok",
    chip: "compatible",
    probedVersion: "1.0.5",
    evidence: "Live probe on 1.0.5. On 1.0.46, grok plugin install and details find the skills, commands and MCP server (static: no signed-in session to run a summon).",
    evidenceHref: `${REPO}/plugins/skill-heaven/PROBE.md`,
    needsInstaller: true,
    commands: [`grok plugin install "${AGENT_PLUGIN_INSTALL.plugin}" --trust`],
    inHarness: false,
    blocked: null,
    update: "Re-run the installer, then grok plugin update.",
    remove: ["grok plugin uninstall skill-heaven", AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "UNSUPPORTED",
    statusNote: "A command-backed status line is possible on Grok but not built.",
    launcher: "grok-zero",
    firstRun: "/summon <what you need>"
  },
  {
    id: "hermes",
    ...PENDING("Hermes"),
    name: "Hermes",
    bin: "hermes",
    chip: "compatible",
    probedVersion: "0.20.0",
    evidence: "Live probe, repeated on 0.20.0 (2026-10-08): plugin installed and enabled, a summon call completed.",
    evidenceHref: `${REPO}/plugins/skill-heaven/PROBE.md`,
    needsInstaller: true,
    commands: [`hermes plugins install "file://${AGENT_PLUGIN_INSTALL.plugin}" --enable`],
    inHarness: false,
    blocked: null,
    update: "Re-run the installer, then reinstall in Hermes. Remove the Hermes registration with Hermes's own plugin manager.",
    // Hermes's own removal command was not verified on the machine that wrote
    // this table (its `--help` could not run), so none is printed.
    remove: [AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "UNSUPPORTED",
    statusNote: "Hermes has no stable public status contribution. Receipts print in the transcript.",
    launcher: "hermes-zero",
    firstRun: "/summon <what you need>"
  },
  {
    id: "agy",
    ...PENDING("Antigravity"),
    name: "Antigravity",
    bin: "agy",
    chip: "compatible",
    probedVersion: "1.3.1",
    evidence: "Live probe on 1.3.1 with your real HOME: agy plugin install loads the skills, commands and the summon server; /skill-heaven:summon and the four surfaces ran.",
    evidenceHref: `${REPO}/packages/agy-zero/PROBE.md`,
    needsInstaller: true,
    commands: [`agy plugin install "${AGENT_PLUGIN_INSTALL.plugin}"`],
    inHarness: false,
    blocked: null,
    update: "Re-run the installer, then agy plugin uninstall skill-heaven and install it again \u2014 Antigravity keeps its own copy.",
    remove: ["agy plugin uninstall skill-heaven", AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "UNSUPPORTED",
    statusNote: "A stacked status command is the target; not built.",
    launcher: "agy-zero",
    // Antigravity namespaces plugin skills: its / menu lists /skill-heaven:summon, and a bare /summon is not a command.
    firstRun: "/skill-heaven:summon <what you need>"
  },
  {
    id: "other",
    ...PENDING("Another"),
    name: "Another Agent Plugins client",
    bin: null,
    chip: "unverified",
    probedVersion: null,
    evidence: "The package follows Agent Plugins 1.0.0. Your client owns registration; it has not been probed here.",
    evidenceHref: "https://agent-plugins.org/specification",
    needsInstaller: true,
    commands: [],
    inHarness: false,
    blocked: `Point your client's own plugin install at ${AGENT_PLUGIN_INSTALL.plugin}. There is no universal registration command.`,
    update: "Re-run the installer; your client may keep its own cached copy.",
    remove: [AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "UNSUPPORTED",
    statusNote: "Depends on your client.",
    launcher: null,
    firstRun: "/summon <what you need>, or the spelling your client lists for the skill-heaven plugin"
  }
];
var CHIP_LABEL = {
  verified: "Verified",
  compatible: "Compatible",
  partial: "Partial",
  unverified: "Unverified",
  "needs-local-probe": "Needs local probe"
};

// packages/status/src/install-plan.ts
var DEFAULT_PLAN_PATHS = {
  pluginDir: AGENT_PLUGIN_INSTALL.plugin,
  marketplaceDir: AGENT_PLUGIN_INSTALL.marketplace,
  consoleDir: `${AGENT_PLUGIN_INSTALL.root}/marketplace/plugins/skill-heaven-console`
};
function renderRun(run, paths) {
  return run.replaceAll("{{PLUGIN_DIR}}", paths.pluginDir).replaceAll("{{MARKETPLACE_DIR}}", paths.marketplaceDir).replaceAll("{{CONSOLE_DIR}}", paths.consoleDir);
}
function render(steps, piece, paths) {
  return steps.map((s) => ({
    ...s,
    run: renderRun(s.run, paths),
    ...s.shell === void 0 ? {} : { shell: renderRun(s.shell, paths) },
    piece
  }));
}
function pick(piece, op) {
  return piece[op];
}
function planProfile(harness, profile, op, paths = DEFAULT_PLAN_PATHS) {
  if (profile === "core") return { kind: "steps", steps: render(pick(harness.core, op), "core", paths) };
  if (harness.consolePiece === null) {
    return { kind: "blocked", reason: harness.fullBlocked ?? `Full is not available on ${harness.name}.` };
  }
  const core = render(pick(harness.core, op), "core", paths);
  const consoleSteps = render(pick(harness.consolePiece, op), "console", paths);
  return { kind: "steps", steps: op === "remove" ? [...consoleSteps, ...core] : [...core, ...consoleSteps] };
}
function planSwitch(harness, from, to, paths = DEFAULT_PLAN_PATHS) {
  if (from === to) return { kind: "steps", steps: [] };
  if (harness.consolePiece === null) {
    return { kind: "blocked", reason: harness.fullBlocked ?? `Full is not available on ${harness.name}.` };
  }
  return {
    kind: "steps",
    steps: render(to === "full" ? harness.consolePiece.register : harness.consolePiece.remove, "console", paths)
  };
}

// packages/status/src/install-epilogue.ts
var START_URL = "https://gaia-research.github.io/gaia-skill-heaven/#/start";
function chipText(h) {
  const chip = CHIP_LABEL[h.chip];
  if (!h.probedVersion) return chip;
  if (h.chip === "verified") return `${chip} (${h.probedVersion})`;
  if (h.chip === "partial") return `${chip} (static check on ${h.probedVersion})`;
  return `${chip} (probed ${h.probedVersion})`;
}
var indent = (n) => " ".repeat(n);
function stepLines(steps, pad) {
  return steps.map((s) => `${indent(pad)}${s.run}`);
}
function harnessBlock(h, input) {
  const { profile, previous, paths } = input;
  const out = [`  ${h.bin.padEnd(8)} ${h.name} - ${chipText(h)}`];
  const core = planProfile(h, "core", "register", paths);
  const coreSteps = core.kind === "steps" ? core.steps : [];
  if (coreSteps[0]?.where === "harness") out.push(`${indent(11)}Inside ${h.name}, type:`);
  out.push(...stepLines(coreSteps, 13));
  if (profile === "full") {
    const full = planProfile(h, "full", "register", paths);
    if (full.kind === "blocked") {
      out.push(`${indent(11)}Full is not available on ${h.name}: ${full.reason}`);
      out.push(`${indent(11)}Core above still works; no console was added.`);
    } else {
      const piece = previous === "core" ? planSwitch(h, "core", "full", paths) : null;
      const consoleSteps = piece && piece.kind === "steps" ? piece.steps : full.steps.filter((s) => s.piece === "console");
      out.push(`${indent(11)}Then add the console (Full):`);
      out.push(...stepLines(consoleSteps, 13));
    }
  } else if (previous === "full" && h.consolePiece) {
    const down = planSwitch(h, "full", "core", paths);
    if (down.kind === "steps" && down.steps.length > 0) {
      out.push(`${indent(11)}You asked for Core and had Full. Remove only the console:`);
      out.push(...stepLines(down.steps, 13));
    }
  }
  const ran = input.ran?.[h.id];
  if (ran) {
    out.push(`${indent(11)}--register ran:`);
    for (const r of ran) out.push(`${indent(13)}${r.ok ? "ok  " : "FAIL"} ${r.run}${r.ok || !r.detail ? "" : ` \u2014 ${r.detail}`}`);
  }
  return out;
}
function renderInstallEpilogue(input) {
  const { profile, paths } = input;
  const pitch = PROFILE_PITCH[profile];
  const found = input.found.map((id) => HARNESS_PATHS.find((h) => h.id === id)).filter((h) => h.bin !== null);
  const missing = HARNESS_PATHS.filter((h) => h.bin !== null && !input.found.includes(h.id));
  const lines = [];
  lines.push(`Installed the portable Skill Heaven Agent Plugin.`);
  lines.push("");
  lines.push(`Profile: ${pitch.name} \u2014 ${pitch.line}`);
  lines.push("");
  lines.push("What changed on this machine");
  lines.push(`  + ${paths.pluginDir}  (the plugin, one directory)`);
  lines.push(`  + ${paths.marketplaceDir}  (a local marketplace that lists it)`);
  if (profile === "full") lines.push(`  + ${paths.consoleDir}  (the console pieces, Full only)`);
  lines.push("  No harness was installed or reconfigured.");
  lines.push("");
  lines.push("Harnesses found on PATH");
  for (const h of found) lines.push(...harnessBlock(h, input));
  if (found.length === 0) {
    lines.push("  (none found)");
    lines.push("  No supported harness was found on PATH. Skill Heaven runs inside a harness you already use; it never installs one.");
    lines.push(`  When you have one, run its command from ${START_URL}`);
  }
  if (missing.length > 0) {
    lines.push("");
    lines.push(`Not found: ${missing.map((h) => h.bin).join(", ")}`);
  }
  lines.push("");
  const other = HARNESS_PATHS.find((h) => h.id === "other");
  lines.push(`${other.name} (${CHIP_LABEL[other.chip]})`);
  lines.push(`  Point your client's own plugin install at ${paths.pluginDir}.`);
  lines.push("  There is no universal registration command.");
  lines.push("");
  lines.push(
    "First run: inside your harness, type /summon <what you need> (Claude Code and Antigravity: /skill-heaven:summon <what you need>)."
  );
  lines.push("Update:    re-run this installer (clients that cache plugins also need their own update).");
  lines.push(
    profile === "full" ? "Switch:    re-run with --profile core to drop only the console; Core keeps working." : "Switch:    re-run with --profile full to add the native console; Core is not touched."
  );
  lines.push(`Remove:    ${paths.uninstall}   (client registrations are removed in each client)`);
  lines.push(`Choose your harness and read what each step does: ${START_URL}`);
  return lines.join("\n");
}

// scripts/install-profile.ts
var MARKER = ".skill-heaven-agent-plugin-install";
function parseOptions(args, env = process.env) {
  const o = { home: env.SKILL_HEAVEN_PLUGIN_HOME ?? join(env.XDG_DATA_HOME ?? join(env.HOME ?? env.USERPROFILE ?? ".", ".local", "share"), "gaia-skill-heaven-agent-plugin"), register: false, uninstall: false, quiet: false, printPath: false };
  if (env.SKILL_HEAVEN_PROFILE) o.profile = env.SKILL_HEAVEN_PROFILE;
  if (env.SKILL_HEAVEN_HARNESS) o.harness = env.SKILL_HEAVEN_HARNESS;
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (["--home", "--source", "--profile", "--harness"].includes(arg)) {
      const value = args[++i];
      if (!value || value.startsWith("--")) throw new Error(`${arg} requires a value`);
      if (arg === "--home") o.home = value;
      if (arg === "--source") o.source = value;
      if (arg === "--profile") o.profile = value;
      if (arg === "--harness") o.harness = value;
    } else if (arg === "--register") o.register = true;
    else if (arg === "--uninstall") o.uninstall = true;
    else if (arg === "--quiet" || arg === "-q") o.quiet = true;
    else if (arg === "--print-path") o.printPath = true;
    else throw new Error(`unknown argument: ${arg}`);
  }
  if (o.profile && o.profile !== "core" && o.profile !== "full") throw new Error("profile must be core or full");
  if (o.harness && !HARNESS_PATHS.some((h) => h.id === o.harness)) throw new Error("unknown harness");
  o.home = resolve(o.home);
  if (o.home === dirname(o.home)) throw new Error("installation root cannot be a filesystem root");
  return o;
}
function pathsFor(home) {
  return { pluginDir: join(home, "marketplace", "plugins", "skill-heaven"), consoleDir: join(home, "marketplace", "plugins", "skill-heaven-console"), marketplaceDir: join(home, "marketplace") };
}
function previousAt(home) {
  if (!existsSync(home)) return null;
  if (lstatSync(home).isSymbolicLink() || !existsSync(join(home, MARKER))) throw new Error(`refusing to change unverified directory: ${home}`);
  if (!existsSync(join(home, "profile.json"))) return null;
  const r = JSON.parse(readFileSync(join(home, "profile.json"), "utf8"));
  if (r.schema !== "skill-heaven/install@1" || !["core", "full"].includes(r.profile) || r.harness !== null && !HARNESS_PATHS.some((h) => h.id === r.harness) || typeof r.registered !== "boolean") throw new Error("invalid installation receipt; refusing mutation");
  return r;
}
function cleanGitEnv() {
  const env = { ...process.env };
  for (const key of Object.keys(env)) if (key.startsWith("GIT_")) delete env[key];
  return { ...env, GIT_CONFIG_NOSYSTEM: "1", GIT_CONFIG_SYSTEM: process.platform === "win32" ? "NUL" : "/dev/null", GIT_CONFIG_GLOBAL: process.platform === "win32" ? "NUL" : "/dev/null" };
}
function gitRepository(path) {
  const env = cleanGitEnv();
  const nullDev = process.platform === "win32" ? "NUL" : "/dev/null";
  for (const args of [["init", "-q"], ["add", "--all"], ["-c", "commit.gpgsign=false", "-c", "user.name=Skill Heaven installer", "-c", "user.email=installer@skill-heaven.invalid", "commit", "--no-gpg-sign", "-qm", "Install Skill Heaven Agent Plugin"]]) {
    const r = spawnSync("git", ["-c", `core.hooksPath=${nullDev}`, ...args], { cwd: path, env, encoding: "utf8" });
    if (r.status !== 0) throw new Error("could not prepare the complete local plugin repository");
  }
}
function executeSteps(steps, paths) {
  for (const s of steps) {
    const data = s;
    if (!data.argv?.length) throw new Error(`no safe argv registration for ${s.run}`);
    const argv = data.argv.map((v) => renderRun(v, paths));
    const result = spawnSync(argv[0], argv.slice(1), { stdio: ["pipe", "inherit", "inherit"], input: data.stdin ?? "", shell: false });
    if (result.status !== 0 || result.error) throw new Error(`host registration failed: ${argv[0]} (exit ${result.status ?? "unknown"}); keep the artifact and retry, do not assume the host cache refreshed`);
  }
}
function consoleSource(h) {
  return h.id === "claude" ? "skill-heaven-console" : `skill-heaven-console-${h.id}`;
}
function required(path) {
  if (!existsSync(path) || lstatSync(path).isSymbolicLink()) throw new Error(`source archive is missing or redirects required artifact: ${path}`);
}
function uninstallScripts(next) {
  writeFileSync(join(next, "uninstall.sh"), `#!/bin/sh
set -eu
ROOT=$(CDPATH= cd -P "$(dirname "$0")" && pwd)
[ -f "$ROOT/${MARKER}" ] && [ -f "$ROOT/marketplace/plugins/skill-heaven/plugin.json" ] || { printf '%s\\n' 'refusing to remove unverified directory' >&2; exit 1; }
exec node "$ROOT/install-profile.mjs" --home "$ROOT" --uninstall --register "$@"
`, { mode: 493 });
  writeFileSync(join(next, "uninstall.ps1"), `$ErrorActionPreference = 'Stop'
if (-not (Test-Path (Join-Path $PSScriptRoot '${MARKER}')) -or -not (Test-Path (Join-Path $PSScriptRoot 'marketplace/plugins/skill-heaven/plugin.json'))) { throw 'refusing to remove unverified directory' }
& node (Join-Path $PSScriptRoot 'install-profile.mjs') --home $PSScriptRoot --uninstall --register @args
if ($LASTEXITCODE -ne 0) { throw 'Uninstall failed' }
`);
}
function install(o) {
  const paths = pathsFor(o.home);
  if (o.printPath) {
    console.log(paths.pluginDir);
    return;
  }
  const previous = previousAt(o.home);
  if (o.uninstall) {
    if (!existsSync(o.home)) {
      console.log(`Skill Heaven Agent Plugin is not installed at ${o.home}`);
      return;
    }
    if ((previous?.registered || previous?.incomplete) && !o.register) throw new Error("registered installation: use --uninstall --register to remove installer-owned host registrations first");
    if (o.register && previous?.harness && (previous.registered || previous.incomplete)) {
      const h2 = HARNESS_PATHS.find((h3) => h3.id === previous.harness);
      const p = planProfile(h2, previous.profile, "remove", paths);
      if (p.kind === "blocked") throw new Error(p.reason);
      executeSteps(p.steps, paths);
    }
    rmSync(o.home, { recursive: true });
    console.log(`Removed the local Skill Heaven Agent Plugin artifact from ${o.home}`);
    console.log(previous?.registered ? "Installer-managed host registrations were removed. Other client-managed copies are untouched." : "Client-managed plugin copies and registrations were not removed.");
    return;
  }
  const profile = o.profile ?? previous?.profile ?? "core";
  const harness = o.harness ?? previous?.harness ?? null;
  const h = harness === null ? null : HARNESS_PATHS.find((h2) => h2.id === harness);
  if (profile === "full" && (!h || h.consolePiece === null)) throw new Error(h?.fullBlocked ?? "Full requires --harness claude|pi|codex|hermes|grok|agy");
  if (o.register && (!h || h.id === "other")) throw new Error("--register requires one known harness; an unknown client owns its own registration");
  if (previous?.harness && previous.harness !== harness && (previous.registered || previous.incomplete)) throw new Error("uninstall the registered harness before changing --harness");
  if (previous?.profile === "full" && profile === "core" && (previous.registered || previous.incomplete) && !o.register) throw new Error("Full \u2192 Core requires --register to remove the installer-owned console registration");
  if (!o.source) throw new Error("install requires an extracted --source archive");
  const source = resolve(o.source);
  for (const file of ["plugin.json", "mcp.json", "skills/summon/SKILL.md", "mcp/skill-summon.mjs"]) required(join(source, "plugins", "skill-heaven", file));
  required(join(source, "scripts", "install-profile.mjs"));
  required(join(source, ".claude-plugin", "marketplace.json"));
  if (profile === "full") required(join(source, "plugins", consoleSource(h)));
  mkdirSync(dirname(o.home), { recursive: true });
  const work = mkdtempSync(join(dirname(o.home), ".gaia-skill-heaven-agent-plugin."));
  const next = join(work, "install"), old = join(work, "old");
  try {
    const staged = pathsFor(next);
    mkdirSync(join(next, "marketplace", "plugins"), { recursive: true });
    cpSync(join(source, "plugins", "skill-heaven"), staged.pluginDir, { recursive: true });
    if (profile === "full") cpSync(join(source, "plugins", consoleSource(h)), staged.consoleDir, { recursive: true });
    const market = JSON.parse(readFileSync(join(source, ".claude-plugin", "marketplace.json"), "utf8"));
    market.plugins = market.plugins.filter((p) => p.source === "./plugins/skill-heaven" || profile === "full" && p.source === "./plugins/skill-heaven-console");
    if (market.plugins.length !== (profile === "full" ? 2 : 1)) throw new Error("could not write the local marketplace manifest");
    mkdirSync(join(next, "marketplace", ".claude-plugin"));
    writeFileSync(join(next, "marketplace", ".claude-plugin", "marketplace.json"), JSON.stringify(market, null, 2) + "\n");
    gitRepository(staged.pluginDir);
    if (profile === "full") gitRepository(staged.consoleDir);
    cpSync(join(source, "scripts", "install-profile.mjs"), join(next, "install-profile.mjs"));
    writeFileSync(join(next, MARKER), "skill-heaven/install@1\n");
    uninstallScripts(next);
    const receipt = { schema: "skill-heaven/install@1", profile, harness, registered: previous?.registered ?? false };
    receipt.incomplete = o.register || previous?.incomplete || false;
    if (o.register && h && previous?.profile === "full" && profile === "core") {
      const down = planSwitch(h, "full", "core", paths);
      if (down.kind === "blocked") throw new Error(down.reason);
      executeSteps(down.steps, paths);
    }
    writeFileSync(join(next, "profile.json"), JSON.stringify(receipt, null, 2) + "\n");
    if (existsSync(o.home)) renameSync(o.home, old);
    try {
      renameSync(next, o.home);
    } catch (e) {
      if (existsSync(old)) renameSync(old, o.home);
      throw e;
    }
    if (o.register && h) {
      const plan = planProfile(h, profile, previous?.registered && previous.profile === profile ? "update" : "register", paths);
      if (plan.kind === "blocked") throw new Error(plan.reason);
      executeSteps(plan.steps, paths);
      receipt.registered = true;
      receipt.incomplete = false;
      writeFileSync(join(o.home, "profile.json"), JSON.stringify(receipt, null, 2) + "\n");
    }
    if (o.quiet) console.log(`${paths.pluginDir}
${paths.marketplaceDir}`);
    else {
      const found = h?.bin ? [h.id] : HARNESS_PATHS.filter((x) => x.bin && onPath(x.bin)).map((x) => x.id);
      console.log(renderInstallEpilogue({ profile, previous: previous?.profile ?? null, found, paths: { ...paths, installHome: o.home, uninstall: join(o.home, process.platform === "win32" ? "uninstall.ps1" : "uninstall.sh") } }));
      if (o.register) console.log(`Registered ${profile} for ${h.name} using its own plugin manager. Restart the harness (Pi: /reload).`);
      else console.log("Artifact staged only. Run the printed registration/removal commands; cached client copies do not refresh automatically.");
    }
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
}
function onPath(bin) {
  const separator = process.platform === "win32" ? ";" : ":";
  return (process.env.PATH ?? "").split(separator).some((dir) => [bin, ...process.platform === "win32" ? [bin + ".exe", bin + ".cmd"] : []].some((name) => existsSync(join(dir, name))));
}
if (process.argv[1] && realpathSync(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    install(parseOptions(process.argv.slice(2)));
  } catch (e) {
    console.error(`skill-heaven-agent-plugin-install: ${e instanceof Error ? e.message : "installation failed"}`);
    process.exitCode = 1;
  }
}
export {
  executeSteps,
  install,
  parseOptions
};
