// @ts-nocheck
// Generated by npm run build:profiles — typed source: scripts/install-profile.ts; do not edit.

// scripts/install-profile.ts
import { spawnSync } from "node:child_process";
import { cpSync, existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// packages/status/src/compat-console.ts
var step = (argv, run, effect) => ({ where: "shell", argv, run, effect });
var piece = (register, update, remove) => ({ register, update, remove });
var degraded = (via, note) => ({ level: "degraded", via, note });
var ROOT = "https://github.com/gaia-research/gaia-skill-heaven/blob/main";
function adapterPath(id) {
  const pi = id === "pi";
  const hermes = id === "hermes";
  const agy = id === "agy";
  const versions = { pi: "1.0.4", codex: "0.161.0", hermes: "0.20.0", grok: "1.0.46", agy: "1.3.1" };
  const register = (console3) => {
    const dir = console3 ? "{{CONSOLE_DIR}}" : "{{PLUGIN_DIR}}";
    const name = console3 ? "skill-heaven-console" : "skill-heaven";
    if (pi) return [step(["pi", "install", dir, "--approve"], `pi install "${dir}" --approve`, `registers only ${name} as a Pi package`)];
    if (id === "codex") return [
      ...console3 ? [] : [step(["codex", "plugin", "marketplace", "add", "{{MARKETPLACE_DIR}}"], 'codex plugin marketplace add "{{MARKETPLACE_DIR}}"', "registers the staged marketplace")],
      step(["codex", "plugin", "add", `${name}@gaia-skill-heaven`], `codex plugin add ${name}@gaia-skill-heaven`, `registers only ${name}`)
    ];
    if (hermes) return [step(["hermes", "plugins", "install", `file://${dir}`, "--enable"], `hermes plugins install "file://${dir}" --enable`, `registers ${name}; staging MUST supply an independent Git root (Hermes clones Git sources)`)];
    if (id === "grok") return [step(["grok", "plugin", "install", dir, "--trust"], `grok plugin install "${dir}" --trust`, `registers only ${name}`)];
    return [step(["agy", "plugin", "install", dir], `agy plugin install "${dir}"`, `registers only ${name}; real HOME required`)];
  };
  const remove = (console3) => {
    const name = console3 ? "skill-heaven-console" : "skill-heaven";
    const dir = console3 ? "{{CONSOLE_DIR}}" : "{{PLUGIN_DIR}}";
    if (pi) return [step(["pi", "remove", dir], `pi remove "${dir}"`, `removes only ${name}`)];
    if (id === "codex") return [step(["codex", "plugin", "remove", `${name}@gaia-skill-heaven`], `codex plugin remove ${name}@gaia-skill-heaven`, `removes only ${name}`)];
    if (hermes) return [
      step(["hermes", "plugins", "disable", name], `hermes plugins disable ${name}`, `disables only ${name}; preserves the host-owned deny-list`),
      step(["hermes", "plugins", "remove", name], `hermes plugins remove ${name}`, `removes only ${name}'s cached plugin directory`)
    ];
    if (agy) return [{ ...step(["agy", "plugin", "uninstall", name], `agy plugin uninstall ${name}`, `uninstalls only ${name}; real HOME preserved`), stdin: "y\n" }];
    return [step(["grok", "plugin", "uninstall", name], `grok plugin uninstall ${name}`, `removes only ${name}`)];
  };
  const update = (console3) => {
    if (pi) return [];
    if (hermes) {
      const steps = register(console3);
      return steps.map((s) => ({ ...s, argv: [...s.argv, "--force"], run: s.run + " --force", effect: s.effect + "; replaces this cached copy" }));
    }
    if (agy) return register(console3);
    if (id === "codex") return [...remove(console3), ...register(console3)];
    return [...remove(console3), ...register(console3)];
  };
  const command = agy ? "/skill-heaven-console:heaven" : "/heaven";
  const report = pi ? "ctx.ui.setWidget (own key, below editor)" : hermes ? "native register_command /heaven report" : "explicit console skill/command (model-mediated)";
  const console2 = {
    kind: pi ? "extension-ui" : "command-backed",
    mechanism: pi ? "Separate Pi extension: own setStatus key and command-opened widget. /lens drafts a preview handoff; /heaven fill prefills only, a human submits through normal tool approval." : `${report}; one canonical renderConsoleText report, no fake HUD or status configuration rewrite.`,
    command,
    commandPrefix: agy ? "skill-heaven:" : "",
    surfaces: {
      status: pi ? { level: "native", via: "ctx.ui.setStatus(skill-heaven-console)", note: "Appends an owned entry; does not replace the footer." } : degraded(report, "Report only, not a persistent status contribution."),
      lens: degraded(pi ? "/lens + /heaven fill" : hermes ? "/lens (printed draft)" : `${command} lens`, pi || hermes ? "Draft only: no tool call, retrieval or materialization until a human submits the handoff through normal host tool approval. Observed preview results use the same shared model." : "Explicit model-mediated preview:true on the existing Core tool; printed handoff, no automatic tool call."),
      session: degraded(report, "Bounded receipt window. Exact session binding required; no newest-directory guess."),
      scope: degraded(report, "Printed controls, not enforcement. Ultra controller remains unavailable."),
      flow: { level: "unsupported", via: report, note: "No implemented, empirically pinned agent-id attribution. Summons attributed to main; no invented agents." },
      trust: degraded(report, "Lists capabilities and limits; does not rate them.")
    },
    observes: { summon: pi ? "observed" : "reported", read: pi ? "observed" : "unavailable", agents: "unavailable", rung: pi ? "observed" : "unavailable" },
    summonTools: pi ? ["summon"] : agy ? ["skill-heaven_skill-summon/summon"] : id === "codex" ? ["mcp__skill-summon__summon"] : [],
    trust: [
      { id: "skill-heaven", profile: "core", kind: "harness runtime package", version: "0.1.2", summary: "Five entropy surfaces and the bundled summon engine.", reads: ["configured skill source"], writes: ["disposable engine session directory"], network: "Core fetches the configured skill source", disable: remove(false)[0].run },
      { id: "skill-heaven-console", profile: "full", kind: pi ? "Pi extension package" : hermes ? "Hermes native Python plugin + Node painter" : "command/skill plugin + Node report", version: "0.1.0", summary: "Read-only projection of the shared console model; independently removable.", reads: pi ? ["exact Core summon results", "successful read events", "active session branch"] : hermes ? ["caller-supplied exact Core sessionRoot ledger"] : ["caller-supplied exact Core sessionRoot ledger", ...agy ? ["optional exact conversation transcript and confined result files"] : []], writes: [], network: pi || hermes ? "none; Lens only drafts a handoff, normal Core calls remain subject to host approval" : "none of its own; explicit model-mediated Lens requests use the existing Core tool", disable: remove(true)[0].run, notes: ["No hidden submission, automatic materialization, daemon, global configuration rewrite or independent summon server.", ...pi ? ["Restored branches cannot prove successful body reads or rung selection; those facts are not replayed."] : ["Without an exact binding, counts are unknown. Command/skill output may pass through the model."]] }
    ],
    probe: { version: versions[id], summary: `Saved ${versions[id]} API/layout evidence informed this adapter. Compiled artifact and synthetic conformance tests are NOT an empirical Full compatibility receipt; live install, Lens and console-only removal still need a probe.`, href: `${ROOT}/plugins/skill-heaven-console-${id}/README.md` }
  };
  return { console: console2, core: piece(register(false), update(false), remove(false)), consolePiece: piece(register(true), update(true), remove(true)), fullBlocked: null };
}

// packages/status/src/compat.ts
var AGENT_PLUGIN_INSTALL = {
  posix: "curl -fsSL https://gaia-research.github.io/gaia-skill-heaven/install-agent-plugin.sh | sh",
  windows: "irm https://gaia-research.github.io/gaia-skill-heaven/install-agent-plugin.ps1 | iex",
  root: "$HOME/.local/share/gaia-skill-heaven-agent-plugin",
  marketplace: "$HOME/.local/share/gaia-skill-heaven-agent-plugin/marketplace",
  plugin: "$HOME/.local/share/gaia-skill-heaven-agent-plugin/marketplace/plugins/skill-heaven",
  uninstall: "$HOME/.local/share/gaia-skill-heaven-agent-plugin/uninstall.sh"
};
var PROFILE_PITCH = {
  core: { name: "Core", line: "The Skill Heaven runtime. Summon and the entropy controls. No extra console UI." },
  full: {
    name: "Full",
    line: "Core, plus the native Skill Heaven console for your harness \u2014 status, Lens, Session, Scope, Flow and Trust where the harness supports them."
  }
};
var PENDING = (name) => ({
  console: {
    kind: "command-backed",
    mechanism: `pending recon for ${name}`,
    command: null,
    commandPrefix: "",
    surfaces: {
      status: { level: "unsupported", via: "pending", note: "pending" },
      lens: { level: "unsupported", via: "pending", note: "pending" },
      session: { level: "unsupported", via: "pending", note: "pending" },
      scope: { level: "unsupported", via: "pending", note: "pending" },
      flow: { level: "unsupported", via: "pending", note: "pending" },
      trust: { level: "unsupported", via: "pending", note: "pending" }
    },
    observes: { summon: "unavailable", read: "unavailable", agents: "unavailable", rung: "unavailable" },
    summonTools: [],
    trust: [],
    probe: { version: null, summary: "pending", href: null }
  },
  core: { register: [], update: [], remove: [] },
  consolePiece: null,
  fullBlocked: "pending recon"
});
var REPO = "https://github.com/gaia-research/gaia-skill-heaven/blob/main";
var HARNESS_PATHS = [
  {
    id: "claude",
    name: "Claude Code",
    bin: "claude",
    chip: "verified",
    probedVersion: "2.1.288",
    evidence: "Fresh-install receipt, 76/76 checks, GitHub main @ fdfd94e.",
    evidenceHref: `${REPO}/docs/RELEASE-ACCEPTANCE.md`,
    needsInstaller: false,
    commands: [
      "/plugin marketplace add gaia-research/gaia-skill-heaven",
      "/plugin install skill-heaven@gaia-skill-heaven"
    ],
    inHarness: true,
    blocked: null,
    update: "claude plugin marketplace update gaia-skill-heaven && claude plugin update skill-heaven@gaia-skill-heaven",
    remove: ["claude plugin uninstall skill-heaven@gaia-skill-heaven"],
    statusIntegration: "APPEND",
    statusNote: "The optional console (preview) adds a status entry beside yours \u2014 it never replaces your statusLine. Probed live in the terminal on 2.1.294; its desktop paint is not probed.",
    launcher: "claude-zero",
    // 2.1.294 refuses a bare /summon: it resolves to the portable skill, which is user-invocable: false.
    firstRun: "/skill-heaven:summon <what you need>",
    console: {
      kind: "pane",
      mechanism: "Claude Code's Mods API (function hooks, early access since 2.1.293): $.ui.status appends a status entry beside your own, an AbovePrompt band carries Lens, and /heaven opens a pane with Session, Scope, Flow and Trust.",
      command: "/heaven",
      commandPrefix: "skill-heaven:",
      surfaces: {
        status: { level: "native", via: "$.ui.status (APPEND \u2014 never touches statusLine)", note: "Probed live in the terminal on 2.1.294; desktop paint is not probed." },
        lens: { level: "native", via: "AbovePrompt band + $.prompt.fill", note: "A button only pre-fills the prompt; you press Enter." },
        session: { level: "native", via: "the /heaven pane", note: "Every field carries an evidence class." },
        scope: { level: "native", via: "the /heaven pane", note: "Rung controls pre-fill commands; nothing runs until you submit." },
        flow: { level: "native", via: "agentId on tool.call and turn.complete", note: "Only agents the host reported appear." },
        trust: { level: "native", via: "the /heaven pane", note: "Lists what the console reads and writes; it does not rate it." }
      },
      observes: { summon: "observed", read: "observed", agents: "observed", rung: "observed" },
      summonTools: ["mcp__plugin_skill-heaven_skill-summon__summon", "mcp__skill-summon__summon"],
      trust: [
        {
          id: "skill-heaven",
          profile: "core",
          kind: "Claude Code plugin",
          version: "0.1.2",
          summary: "The runtime: five commands and one bundled MCP server (skill-summon).",
          reads: ["the skill source you configure (network, by the summon tool)"],
          writes: ["a disposable session directory under your temp dir"],
          network: "the summon tool fetches the skill source",
          disable: "claude plugin uninstall skill-heaven@gaia-skill-heaven"
        },
        {
          id: "skill-heaven-console",
          profile: "full",
          kind: "Claude Code plugin (Mods, preview)",
          version: "0.1.0",
          summary: "The console: a status entry, the Lens band and the /heaven pane. Runs inside Claude Code as local code.",
          notes: ["/lens and /heaven print a one-line result that the model can read. It is fixed text and carries nothing a skill source supplied."],
          reads: ["summon tool results", "your /skill-* commands", "Read and Agent tool calls \u2014 to observe, never to change"],
          writes: ["nothing to disk", "session-only $.state"],
          network: "none of its own; /lens calls the bundled summon tool, which fetches the skill source",
          disable: "claude plugin uninstall skill-heaven-console@gaia-skill-heaven"
        }
      ],
      probe: {
        version: "2.1.294",
        summary: "the console was probed live in the terminal on 2.1.294; desktop paint is not probed",
        href: `${REPO}/plugins/skill-heaven-console/README.md`
      }
    },
    core: {
      register: [
        { where: "shell", run: 'claude plugin marketplace add "{{MARKETPLACE_DIR}}"', argv: ["claude", "plugin", "marketplace", "add", "{{MARKETPLACE_DIR}}"], effect: "adds the reviewed staged local marketplace to Claude Code's plugin registry" },
        { where: "harness", run: "/plugin install skill-heaven@gaia-skill-heaven", shell: "claude plugin install skill-heaven@gaia-skill-heaven", argv: ["claude", "plugin", "install", "skill-heaven@gaia-skill-heaven"], effect: "installs the skill-heaven plugin (runtime only)" }
      ],
      update: [
        { where: "shell", run: "claude plugin marketplace update gaia-skill-heaven", argv: ["claude", "plugin", "marketplace", "update", "gaia-skill-heaven"], effect: "refreshes the marketplace listing" },
        { where: "shell", run: "claude plugin uninstall skill-heaven@gaia-skill-heaven", argv: ["claude", "plugin", "uninstall", "skill-heaven@gaia-skill-heaven"], effect: "removes only the old cached runtime registration before reinstall" },
        { where: "shell", run: "claude plugin install skill-heaven@gaia-skill-heaven", argv: ["claude", "plugin", "install", "skill-heaven@gaia-skill-heaven"], effect: "installs the staged candidate even when the version string is unchanged" }
      ],
      remove: [{ where: "shell", run: "claude plugin uninstall skill-heaven@gaia-skill-heaven", argv: ["claude", "plugin", "uninstall", "skill-heaven@gaia-skill-heaven"], effect: "removes the plugin" }]
    },
    consolePiece: {
      register: [
        { where: "harness", run: "/plugin install skill-heaven-console@gaia-skill-heaven", shell: "claude plugin install skill-heaven-console@gaia-skill-heaven", argv: ["claude", "plugin", "install", "skill-heaven-console@gaia-skill-heaven"], effect: "installs the console plugin beside skill-heaven" }
      ],
      update: [
        { where: "shell", run: "claude plugin marketplace update gaia-skill-heaven", argv: ["claude", "plugin", "marketplace", "update", "gaia-skill-heaven"], effect: "refreshes the registered local marketplace" },
        { where: "shell", run: "claude plugin uninstall skill-heaven-console@gaia-skill-heaven", argv: ["claude", "plugin", "uninstall", "skill-heaven-console@gaia-skill-heaven"], effect: "removes only the old cached console before reinstall" },
        { where: "shell", run: "claude plugin install skill-heaven-console@gaia-skill-heaven", argv: ["claude", "plugin", "install", "skill-heaven-console@gaia-skill-heaven"], effect: "installs the staged console even when its version string is unchanged" }
      ],
      remove: [{ where: "shell", run: "claude plugin uninstall skill-heaven-console@gaia-skill-heaven", argv: ["claude", "plugin", "uninstall", "skill-heaven-console@gaia-skill-heaven"], effect: "removes only the console; skill-heaven is unchanged" }]
    },
    fullBlocked: null
  },
  {
    id: "codex",
    ...adapterPath("codex"),
    name: "Codex",
    bin: "codex",
    chip: "compatible",
    probedVersion: "0.161.0",
    evidence: "Live smoke on 0.161.0: plugin added, codex mcp list resolves skill-summon, a summon call completed. Headless codex exec asks approval for MCP calls. Surfaces last probed on 0.146.0.",
    evidenceHref: `${REPO}/plugins/skill-heaven/PROBE.md`,
    needsInstaller: true,
    commands: [
      `codex plugin marketplace add "${AGENT_PLUGIN_INSTALL.marketplace}"`,
      "codex plugin add skill-heaven@gaia-skill-heaven"
    ],
    inHarness: false,
    blocked: null,
    update: "Re-run the installer, then reinstall in Codex \u2014 Codex keeps its own cached copy.",
    remove: ["codex plugin remove skill-heaven@gaia-skill-heaven", AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "UNSUPPORTED",
    statusNote: "Codex has no public status contribution API. Summon receipts still print in the transcript.",
    launcher: "codex-zero",
    firstRun: "/summon <what you need>"
  },
  {
    id: "pi",
    ...adapterPath("pi"),
    name: "Pi",
    bin: "pi",
    chip: "compatible",
    probedVersion: "1.0.4",
    evidence: "Live probe on 1.0.4: pi install, five commands, summon materialized a skill, the four surfaces expanded. The adapter keeps its own summon tool rather than Pi's MCP runtime, which an MCP extension can replace.",
    evidenceHref: `${REPO}/plugins/skill-heaven/dev.skill-heaven.pi/PROBE.md`,
    needsInstaller: true,
    commands: [`pi install "${AGENT_PLUGIN_INSTALL.plugin}" --approve`],
    inHarness: false,
    blocked: null,
    update: "Re-run the installer, then pi update.",
    remove: [`pi remove "${AGENT_PLUGIN_INSTALL.plugin}"`, AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "NATIVE SLOT",
    statusNote: "Full adds a separate extension with its own setStatus key (API probed on 1.0.4); the new adapter's live TUI paint remains unprobed. Core has no console.",
    launcher: "pi-zero",
    firstRun: "/summon <what you need>"
  },
  {
    id: "grok",
    ...adapterPath("grok"),
    name: "Grok",
    bin: "grok",
    chip: "compatible",
    probedVersion: "1.0.5",
    evidence: "Live probe on 1.0.5. On 1.0.46, grok plugin install and details find the skills, commands and MCP server (static: no signed-in session to run a summon).",
    evidenceHref: `${REPO}/plugins/skill-heaven/PROBE.md`,
    needsInstaller: true,
    commands: [`grok plugin install "${AGENT_PLUGIN_INSTALL.plugin}" --trust`],
    inHarness: false,
    blocked: null,
    update: "Re-run the installer, then grok plugin update.",
    remove: ["grok plugin uninstall skill-heaven", AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "UNSUPPORTED",
    statusNote: "Full carries Status in an explicit command-backed report, not a persistent HUD.",
    launcher: "grok-zero",
    firstRun: "/summon <what you need>"
  },
  {
    id: "hermes",
    ...adapterPath("hermes"),
    name: "Hermes",
    bin: "hermes",
    chip: "compatible",
    probedVersion: "0.20.0",
    evidence: "Live probe, repeated on 0.20.0 (2026-10-08): plugin installed and enabled, a summon call completed.",
    evidenceHref: `${REPO}/plugins/skill-heaven/PROBE.md`,
    needsInstaller: true,
    commands: [`hermes plugins install "file://${AGENT_PLUGIN_INSTALL.plugin}" --enable`],
    inHarness: false,
    blocked: null,
    update: "Re-run the installer, then reinstall in Hermes. Remove the Hermes registration with Hermes's own plugin manager.",
    // Hermes's own removal command was not verified on the machine that wrote
    // this table (its `--help` could not run), so none is printed.
    remove: [AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "UNSUPPORTED",
    statusNote: "Hermes has no stable public status contribution. Receipts print in the transcript.",
    launcher: "hermes-zero",
    firstRun: "/summon <what you need>"
  },
  {
    id: "agy",
    ...adapterPath("agy"),
    name: "Antigravity",
    bin: "agy",
    chip: "compatible",
    probedVersion: "1.3.1",
    evidence: "Live probe on 1.3.1 with your real HOME: agy plugin install loads the skills, commands and the summon server; /skill-heaven:summon and the four surfaces ran.",
    evidenceHref: `${REPO}/packages/agy-zero/PROBE.md`,
    needsInstaller: true,
    commands: [`agy plugin install "${AGENT_PLUGIN_INSTALL.plugin}"`],
    inHarness: false,
    blocked: null,
    update: "Re-run the installer, then agy plugin uninstall skill-heaven and install it again \u2014 Antigravity keeps its own copy.",
    remove: ["agy plugin uninstall skill-heaven", AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "UNSUPPORTED",
    statusNote: "Full carries Status in an explicit skill report. No user statusLine is installed or rewritten.",
    launcher: "agy-zero",
    // Antigravity namespaces plugin skills: its / menu lists /skill-heaven:summon, and a bare /summon is not a command.
    firstRun: "/skill-heaven:summon <what you need>"
  },
  {
    id: "other",
    ...PENDING("Another"),
    name: "Another Agent Plugins client",
    bin: null,
    chip: "unverified",
    probedVersion: null,
    evidence: "The package follows Agent Plugins 1.0.0. Your client owns registration; it has not been probed here.",
    evidenceHref: "https://agent-plugins.org/specification",
    needsInstaller: true,
    commands: [],
    inHarness: false,
    blocked: `Point your client's own plugin install at ${AGENT_PLUGIN_INSTALL.plugin}. There is no universal registration command.`,
    update: "Re-run the installer; your client may keep its own cached copy.",
    remove: [AGENT_PLUGIN_INSTALL.uninstall],
    statusIntegration: "UNSUPPORTED",
    statusNote: "Depends on your client.",
    launcher: null,
    firstRun: "/summon <what you need>, or the spelling your client lists for the skill-heaven plugin"
  }
];
var CHIP_LABEL = {
  verified: "Verified",
  compatible: "Compatible",
  partial: "Partial",
  unverified: "Unverified",
  "needs-local-probe": "Needs local probe"
};

// packages/status/src/install-plan.ts
var DEFAULT_PLAN_PATHS = {
  pluginDir: AGENT_PLUGIN_INSTALL.plugin,
  marketplaceDir: AGENT_PLUGIN_INSTALL.marketplace,
  consoleDir: `${AGENT_PLUGIN_INSTALL.root}/marketplace/plugins/skill-heaven-console`
};
function renderRun(run, paths) {
  return run.replaceAll("{{PLUGIN_DIR}}", paths.pluginDir).replaceAll("{{MARKETPLACE_DIR}}", paths.marketplaceDir).replaceAll("{{CONSOLE_DIR}}", paths.consoleDir);
}
function render(steps, piece2, paths) {
  return steps.map((s) => ({
    ...s,
    run: renderRun(s.run, paths),
    ...s.shell === void 0 ? {} : { shell: renderRun(s.shell, paths) },
    piece: piece2
  }));
}
function pick(piece2, op) {
  return piece2[op];
}
function planProfile(harness, profile, op, paths = DEFAULT_PLAN_PATHS) {
  if (profile === "core") return { kind: "steps", steps: render(pick(harness.core, op), "core", paths) };
  if (harness.consolePiece === null) {
    return { kind: "blocked", reason: harness.fullBlocked ?? `Full is not available on ${harness.name}.` };
  }
  const core = render(pick(harness.core, op), "core", paths);
  const consoleSteps = render(pick(harness.consolePiece, op), "console", paths);
  return { kind: "steps", steps: op === "remove" ? [...consoleSteps, ...core] : [...core, ...consoleSteps] };
}
function planSwitch(harness, from, to, paths = DEFAULT_PLAN_PATHS) {
  if (from === to) return { kind: "steps", steps: [] };
  if (harness.consolePiece === null) {
    return { kind: "blocked", reason: harness.fullBlocked ?? `Full is not available on ${harness.name}.` };
  }
  return {
    kind: "steps",
    steps: render(to === "full" ? harness.consolePiece.register : harness.consolePiece.remove, "console", paths)
  };
}

// packages/status/src/install-epilogue.ts
var START_URL = "https://gaia-research.github.io/gaia-skill-heaven/#/start";
function chipText(h) {
  const chip = CHIP_LABEL[h.chip];
  if (!h.probedVersion) return chip;
  if (h.chip === "verified") return `${chip} (${h.probedVersion})`;
  if (h.chip === "partial") return `${chip} (static check on ${h.probedVersion})`;
  return `${chip} (probed ${h.probedVersion})`;
}
var indent = (n) => " ".repeat(n);
function stepLines(steps, pad) {
  return steps.map((s) => `${indent(pad)}${s.run}`);
}
function harnessBlock(h, input) {
  const { profile, previous, paths } = input;
  const out = [`  ${h.bin.padEnd(8)} ${h.name} - ${chipText(h)}`];
  const core = planProfile(h, "core", "register", paths);
  const coreSteps = core.kind === "steps" ? core.steps : [];
  if (coreSteps[0]?.where === "harness") out.push(`${indent(11)}Inside ${h.name}, type:`);
  out.push(...stepLines(coreSteps, 13));
  if (profile === "full") {
    const full = planProfile(h, "full", "register", paths);
    if (full.kind === "blocked") {
      out.push(`${indent(11)}Full is not available on ${h.name}: ${full.reason}`);
      out.push(`${indent(11)}Core above still works; no console was added.`);
    } else {
      const piece2 = previous === "core" ? planSwitch(h, "core", "full", paths) : null;
      const consoleSteps = piece2 && piece2.kind === "steps" ? piece2.steps : full.steps.filter((s) => s.piece === "console");
      out.push(`${indent(11)}Then add the console (Full):`);
      out.push(...stepLines(consoleSteps, 13));
    }
  } else if (previous === "full" && h.consolePiece) {
    const down = planSwitch(h, "full", "core", paths);
    if (down.kind === "steps" && down.steps.length > 0) {
      out.push(`${indent(11)}You asked for Core and had Full. Remove only the console:`);
      out.push(...stepLines(down.steps, 13));
    }
  }
  const ran = input.ran?.[h.id];
  if (ran) {
    out.push(`${indent(11)}--register ran:`);
    for (const r of ran) out.push(`${indent(13)}${r.ok ? "ok  " : "FAIL"} ${r.run}${r.ok || !r.detail ? "" : ` \u2014 ${r.detail}`}`);
  }
  return out;
}
function renderInstallEpilogue(input) {
  const { profile, paths } = input;
  const pitch = PROFILE_PITCH[profile];
  const found = input.found.map((id) => HARNESS_PATHS.find((h) => h.id === id)).filter((h) => h.bin !== null);
  const missing = HARNESS_PATHS.filter((h) => h.bin !== null && !input.found.includes(h.id));
  const lines = [];
  lines.push(`Installed the portable Skill Heaven Agent Plugin.`);
  lines.push("");
  lines.push(`Profile: ${pitch.name} \u2014 ${pitch.line}`);
  lines.push("");
  lines.push("What changed on this machine");
  lines.push(`  + ${paths.pluginDir}  (the plugin, one directory)`);
  lines.push(`  + ${paths.marketplaceDir}  (a local marketplace that lists it)`);
  if (profile === "full") lines.push(`  + ${paths.consoleDir}  (the console pieces, Full only)`);
  lines.push("  No harness was installed or reconfigured.");
  lines.push("");
  lines.push("Harnesses found on PATH");
  for (const h of found) lines.push(...harnessBlock(h, input));
  if (found.length === 0) {
    lines.push("  (none found)");
    lines.push("  No supported harness was found on PATH. Skill Heaven runs inside a harness you already use; it never installs one.");
    lines.push(`  When you have one, run its command from ${START_URL}`);
  }
  if (missing.length > 0) {
    lines.push("");
    lines.push(`Not found: ${missing.map((h) => h.bin).join(", ")}`);
  }
  lines.push("");
  const other = HARNESS_PATHS.find((h) => h.id === "other");
  lines.push(`${other.name} (${CHIP_LABEL[other.chip]})`);
  lines.push(`  Point your client's own plugin install at ${paths.pluginDir}.`);
  lines.push("  There is no universal registration command.");
  lines.push("");
  lines.push(
    "First run: inside your harness, type /summon <what you need> (Claude Code and Antigravity: /skill-heaven:summon <what you need>)."
  );
  lines.push("Update:    re-run this installer (clients that cache plugins also need their own update).");
  lines.push(
    profile === "full" ? "Switch:    re-run with --profile core to drop only the console; Core keeps working." : "Switch:    re-run with --profile full to add the native console; Core is not touched."
  );
  lines.push(`Remove:    ${paths.uninstall}   (client registrations are removed in each client)`);
  lines.push(`Choose your harness and read what each step does: ${START_URL}`);
  return lines.join("\n");
}

// scripts/install-profile.ts
var MARKER = ".skill-heaven-agent-plugin-install";
function parseOptions(args, env = process.env) {
  const o = { home: env.SKILL_HEAVEN_PLUGIN_HOME ?? join(env.XDG_DATA_HOME ?? join(env.HOME ?? env.USERPROFILE ?? ".", ".local", "share"), "gaia-skill-heaven-agent-plugin"), register: false, uninstall: false, quiet: false, printPath: false };
  if (env.SKILL_HEAVEN_PROFILE) o.profile = env.SKILL_HEAVEN_PROFILE;
  if (env.SKILL_HEAVEN_HARNESS) o.harness = env.SKILL_HEAVEN_HARNESS;
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (["--home", "--source", "--profile", "--harness"].includes(arg)) {
      const value = args[++i];
      if (!value || value.startsWith("--")) throw new Error(`${arg} requires a value`);
      if (arg === "--home") o.home = value;
      if (arg === "--source") o.source = value;
      if (arg === "--profile") o.profile = value;
      if (arg === "--harness") o.harness = value;
    } else if (arg === "--register") o.register = true;
    else if (arg === "--uninstall") o.uninstall = true;
    else if (arg === "--quiet" || arg === "-q") o.quiet = true;
    else if (arg === "--print-path") o.printPath = true;
    else throw new Error(`unknown argument: ${arg}`);
  }
  if (o.profile && o.profile !== "core" && o.profile !== "full") throw new Error("profile must be core or full");
  if (o.harness && !HARNESS_PATHS.some((h) => h.id === o.harness)) throw new Error("unknown harness");
  o.home = resolve(o.home);
  if (o.home === dirname(o.home)) throw new Error("installation root cannot be a filesystem root");
  return o;
}
function pathsFor(home) {
  return { pluginDir: join(home, "marketplace", "plugins", "skill-heaven"), consoleDir: join(home, "marketplace", "plugins", "skill-heaven-console"), marketplaceDir: join(home, "marketplace") };
}
function previousAt(home) {
  if (!existsSync(home)) return null;
  if (lstatSync(home).isSymbolicLink() || !existsSync(join(home, MARKER))) throw new Error(`refusing to change unverified directory: ${home}`);
  if (!existsSync(join(home, "profile.json"))) return null;
  const r = JSON.parse(readFileSync(join(home, "profile.json"), "utf8"));
  if (r.schema !== "skill-heaven/install@1" || !["core", "full"].includes(r.profile) || r.harness !== null && !HARNESS_PATHS.some((h) => h.id === r.harness) || typeof r.registered !== "boolean") throw new Error("invalid installation receipt; refusing mutation");
  if (r.incomplete !== void 0 && typeof r.incomplete !== "boolean") throw new Error("invalid installation receipt; refusing mutation");
  if (r.incomplete && !r.transaction) throw new Error("legacy incomplete receipt: host ownership is unknown; recover the original registration manually before changing this artifact");
  if (r.transaction) {
    const t = r.transaction;
    if (!r.incomplete || !r.harness || !["register", "update", "switch", "remove"].includes(t.operation) || !["core", "full"].includes(t.target) || t.previousProfile !== null && !["core", "full"].includes(t.previousProfile) || typeof t.staged !== "boolean" || !Array.isArray(t.steps) || !Array.isArray(t.completed) || t.steps.some((s) => typeof s !== "string") || t.completed.some((s) => typeof s !== "string") || t.completed.length > t.steps.length || t.completed.some((s, i) => s !== t.steps[i]) || t.operation === "register" && (r.registered || t.previousProfile !== null) || t.operation !== "register" && (!r.registered || t.previousProfile === null) || t.operation === "switch" && t.previousProfile === t.target || t.operation !== "switch" && t.previousProfile !== null && t.previousProfile !== t.target || r.profile !== (t.staged ? t.target : t.previousProfile) || !t.staged && !(t.operation === "switch" && t.target === "core")) throw new Error("invalid transaction checkpoint; refusing mutation");
    let steps;
    try {
      steps = transactionSteps(r.harness, t, pathsFor(home));
    } catch {
      throw new Error("operation contract unavailable; keep the artifact and checkpoint, recover with the original installer contract before retrying");
    }
    if (JSON.stringify(t.steps) !== JSON.stringify(steps.map(stepIdentity))) throw new Error("operation contract changed; keep the artifact and checkpoint, recover with the original installer contract before retrying");
    if (t.pending !== void 0) throw new Error("interrupted host step has an unknown outcome; keep sources and checkpoint, reconcile that canonical step with the host before retrying; automatic removal is unsafe");
  }
  return r;
}
function saveReceipt(home, receipt) {
  const file = join(home, "profile.json");
  writeFileSync(file + ".next", JSON.stringify(receipt, null, 2) + "\n");
  renameSync(file + ".next", file);
}
function stepIdentity(s) {
  return JSON.stringify({ piece: s.piece, run: s.run, argv: s.argv, stdin: s.stdin ?? "" });
}
function transactionSteps(harness, t, paths) {
  const h = HARNESS_PATHS.find((h2) => h2.id === harness);
  const plan = t.operation === "switch" ? planSwitch(h, t.previousProfile, t.target, paths) : planProfile(h, t.target, t.operation, paths);
  if (plan.kind === "blocked") throw new Error(plan.reason);
  return plan.steps;
}
function checkpoint(home, receipt) {
  const t = receipt.transaction;
  const steps = transactionSteps(receipt.harness, t, pathsFor(home));
  for (let i = t.completed.length; i < steps.length; i++) {
    t.pending = stepIdentity(steps[i]);
    saveReceipt(home, receipt);
    try {
      executeSteps([steps[i]], pathsFor(home));
    } catch (e) {
      delete t.pending;
      saveReceipt(home, receipt);
      throw e;
    }
    t.completed.push(t.pending);
    delete t.pending;
    saveReceipt(home, receipt);
  }
}
function finish(home, receipt) {
  receipt.registered = true;
  receipt.incomplete = false;
  delete receipt.transaction;
  saveReceipt(home, receipt);
}
function cleanGitEnv() {
  const env = { ...process.env };
  for (const key of Object.keys(env)) if (key.startsWith("GIT_")) delete env[key];
  return { ...env, GIT_CONFIG_NOSYSTEM: "1", GIT_CONFIG_SYSTEM: process.platform === "win32" ? "NUL" : "/dev/null", GIT_CONFIG_GLOBAL: process.platform === "win32" ? "NUL" : "/dev/null" };
}
function gitRepository(path) {
  const env = cleanGitEnv();
  const nullDev = process.platform === "win32" ? "NUL" : "/dev/null";
  for (const args of [["init", "-q"], ["add", "--all"], ["-c", "commit.gpgsign=false", "-c", "user.name=Skill Heaven installer", "-c", "user.email=installer@skill-heaven.invalid", "commit", "--no-gpg-sign", "-qm", "Install Skill Heaven Agent Plugin"]]) {
    const r = spawnSync("git", ["-c", `core.hooksPath=${nullDev}`, ...args], { cwd: path, env, encoding: "utf8" });
    if (r.status !== 0) throw new Error("could not prepare the complete local plugin repository");
  }
}
function executeSteps(steps, paths) {
  for (const s of steps) {
    const data = s;
    if (!data.argv?.length) throw new Error(`no safe argv registration for ${s.run}`);
    const argv = data.argv.map((v) => renderRun(v, paths));
    const result = spawnSync(argv[0], argv.slice(1), { stdio: ["pipe", "inherit", "inherit"], input: data.stdin ?? "", shell: false });
    if (result.status !== 0 || result.error) throw new Error(`host registration failed: ${argv[0]} (exit ${result.status ?? "unknown"}); keep the artifact and retry, do not assume the host cache refreshed`);
  }
}
function consoleSource(h) {
  return h.id === "claude" ? "skill-heaven-console" : `skill-heaven-console-${h.id}`;
}
function required(path) {
  if (!existsSync(path) || lstatSync(path).isSymbolicLink()) throw new Error(`source archive is missing or redirects required artifact: ${path}`);
}
function uninstallScripts(next) {
  writeFileSync(join(next, "uninstall.sh"), `#!/bin/sh
set -eu
ROOT=$(CDPATH= cd -P "$(dirname "$0")" && pwd)
[ -f "$ROOT/${MARKER}" ] && [ -f "$ROOT/marketplace/plugins/skill-heaven/plugin.json" ] || { printf '%s\\n' 'refusing to remove unverified directory' >&2; exit 1; }
exec node "$ROOT/install-profile.mjs" --home "$ROOT" --uninstall --register "$@"
`, { mode: 493 });
  writeFileSync(join(next, "uninstall.ps1"), `$ErrorActionPreference = 'Stop'
if (-not (Test-Path (Join-Path $PSScriptRoot '${MARKER}')) -or -not (Test-Path (Join-Path $PSScriptRoot 'marketplace/plugins/skill-heaven/plugin.json'))) { throw 'refusing to remove unverified directory' }
& node (Join-Path $PSScriptRoot 'install-profile.mjs') --home $PSScriptRoot --uninstall --register @args
if ($LASTEXITCODE -ne 0) { throw 'Uninstall failed' }
`);
}
function install(o) {
  const paths = pathsFor(o.home);
  if (o.printPath) {
    console.log(paths.pluginDir);
    return;
  }
  const previous = previousAt(o.home);
  if (previous?.harness && o.harness && previous.harness !== o.harness && (previous.registered || previous.incomplete)) throw new Error("uninstall the registered harness before changing --harness");
  if (previous?.transaction) {
    const t = previous.transaction;
    if (!o.register || o.uninstall !== (t.operation === "remove") || o.profile && o.profile !== t.target) throw new Error(`unfinished ${t.operation}: keep the artifact; retry --register${t.operation === "remove" ? " --uninstall" : ` --profile ${t.target}`} to resume the exact operation before requesting another operation; automatic partial-registration cleanup is unsafe`);
    if (t.staged && t.operation !== "remove") {
      checkpoint(o.home, previous);
      finish(o.home, previous);
      console.log(`Resumed ${t.operation} for ${previous.harness}.`);
      return;
    }
  }
  if (o.uninstall) {
    if (!existsSync(o.home)) {
      console.log(`Skill Heaven Agent Plugin is not installed at ${o.home}`);
      return;
    }
    if ((previous?.registered || previous?.incomplete) && !o.register) throw new Error("registered installation: use --uninstall --register to remove installer-owned host registrations first");
    if (o.register && previous?.harness && (previous.registered || previous.incomplete)) {
      const h2 = HARNESS_PATHS.find((h3) => h3.id === previous.harness);
      if (!previous.transaction) {
        const t = { operation: "remove", previousProfile: previous.profile, target: previous.profile, steps: [], completed: [], staged: true };
        t.steps = transactionSteps(h2.id, t, paths).map(stepIdentity);
        previous.transaction = t;
        previous.incomplete = true;
        saveReceipt(o.home, previous);
      }
      checkpoint(o.home, previous);
    }
    rmSync(o.home, { recursive: true });
    console.log(`Removed the local Skill Heaven Agent Plugin artifact from ${o.home}`);
    console.log(previous?.registered ? "Installer-managed host registrations were removed. Other client-managed copies are untouched." : "Client-managed plugin copies and registrations were not removed.");
    return;
  }
  const profile = o.profile ?? previous?.transaction?.target ?? previous?.profile ?? "core";
  const harness = o.harness ?? previous?.harness ?? null;
  const h = harness === null ? null : HARNESS_PATHS.find((h2) => h2.id === harness);
  if (profile === "full" && (!h || h.consolePiece === null)) throw new Error(h?.fullBlocked ?? "Full requires --harness claude|pi|codex|hermes|grok|agy");
  if (o.register && (!h || h.id === "other")) throw new Error("--register requires one known harness; an unknown client owns its own registration");
  if (previous?.harness && previous.harness !== harness && (previous.registered || previous.incomplete)) throw new Error("uninstall the registered harness before changing --harness");
  if (previous?.registered && previous.profile !== profile && !o.register) throw new Error("registered profile switch requires --register to change only the installer-owned console registration");
  if (!o.source) throw new Error("install requires an extracted --source archive");
  const source = resolve(o.source);
  for (const file of ["plugin.json", "mcp.json", "skills/summon/SKILL.md", "mcp/skill-summon.mjs"]) required(join(source, "plugins", "skill-heaven", file));
  required(join(source, "scripts", "install-profile.mjs"));
  required(join(source, ".claude-plugin", "marketplace.json"));
  if (profile === "full") required(join(source, "plugins", consoleSource(h)));
  mkdirSync(dirname(o.home), { recursive: true });
  const work = mkdtempSync(join(dirname(o.home), ".gaia-skill-heaven-agent-plugin."));
  const next = join(work, "install"), old = join(work, "old");
  try {
    const staged = pathsFor(next);
    mkdirSync(join(next, "marketplace", "plugins"), { recursive: true });
    cpSync(join(source, "plugins", "skill-heaven"), staged.pluginDir, { recursive: true });
    if (profile === "full") cpSync(join(source, "plugins", consoleSource(h)), staged.consoleDir, { recursive: true });
    const market = JSON.parse(readFileSync(join(source, ".claude-plugin", "marketplace.json"), "utf8"));
    market.plugins = market.plugins.filter((p) => p.source === "./plugins/skill-heaven" || profile === "full" && p.source === "./plugins/skill-heaven-console");
    if (market.plugins.length !== (profile === "full" ? 2 : 1)) throw new Error("could not write the local marketplace manifest");
    mkdirSync(join(next, "marketplace", ".claude-plugin"));
    writeFileSync(join(next, "marketplace", ".claude-plugin", "marketplace.json"), JSON.stringify(market, null, 2) + "\n");
    gitRepository(staged.marketplaceDir);
    gitRepository(staged.pluginDir);
    if (profile === "full") gitRepository(staged.consoleDir);
    cpSync(join(source, "scripts", "install-profile.mjs"), join(next, "install-profile.mjs"));
    writeFileSync(join(next, MARKER), "skill-heaven/install@1\n");
    uninstallScripts(next);
    const receipt = { schema: "skill-heaven/install@1", profile, harness, registered: previous?.registered ?? false, incomplete: false };
    if (o.register && h) {
      const t = previous?.transaction ?? {
        operation: !previous?.registered ? "register" : previous.profile === profile ? "update" : "switch",
        previousProfile: previous?.registered ? previous.profile : null,
        target: profile,
        steps: [],
        completed: [],
        staged: true
      };
      if (!previous?.transaction) t.steps = transactionSteps(h.id, t, paths).map(stepIdentity);
      receipt.transaction = t;
      receipt.incomplete = true;
      if (t.operation === "switch" && profile === "core") {
        t.staged = false;
        previous.transaction = t;
        previous.incomplete = true;
        saveReceipt(o.home, previous);
        checkpoint(o.home, previous);
      }
      receipt.transaction = { ...t, staged: true };
    }
    saveReceipt(next, receipt);
    if (existsSync(o.home)) renameSync(o.home, old);
    try {
      renameSync(next, o.home);
    } catch (e) {
      if (existsSync(old)) {
        try {
          renameSync(old, o.home);
        } catch {
          throw new Error(`could not restore the previous artifact; it is preserved at ${old}; restore it to ${o.home} before retrying`);
        }
      }
      throw e;
    }
    if (o.register && h) {
      checkpoint(o.home, receipt);
      finish(o.home, receipt);
    }
    if (o.quiet) console.log(`${paths.pluginDir}
${paths.marketplaceDir}`);
    else {
      const found = h?.bin ? [h.id] : HARNESS_PATHS.filter((x) => x.bin && onPath(x.bin)).map((x) => x.id);
      console.log(renderInstallEpilogue({ profile, previous: previous?.profile ?? null, found, paths: { ...paths, installHome: o.home, uninstall: join(o.home, process.platform === "win32" ? "uninstall.ps1" : "uninstall.sh") } }));
      if (o.register) console.log(`Registered ${profile} for ${h.name} using its own plugin manager. Restart the harness (Pi: /reload).`);
      else console.log("Artifact staged only. Run the printed registration/removal commands; cached client copies do not refresh automatically.");
    }
  } finally {
    if (!(existsSync(old) && !existsSync(o.home))) rmSync(work, { recursive: true, force: true });
  }
}
function onPath(bin) {
  const separator = process.platform === "win32" ? ";" : ":";
  return (process.env.PATH ?? "").split(separator).some((dir) => [bin, ...process.platform === "win32" ? [bin + ".exe", bin + ".cmd"] : []].some((name) => existsSync(join(dir, name))));
}
if (process.argv[1] && realpathSync(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    install(parseOptions(process.argv.slice(2)));
  } catch (e) {
    console.error(`skill-heaven-agent-plugin-install: ${e instanceof Error ? e.message : "installation failed"}`);
    process.exitCode = 1;
  }
}
export {
  executeSteps,
  install,
  parseOptions
};
